# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SBO",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, verbose_name=b"Date Added"),
                ),
                ("date_observed", models.DateTimeField(verbose_name=b"Date Observed")),
                ("task", models.TextField(max_length=500)),
                ("behavior", models.TextField(max_length=500)),
                (
                    "behavior_type",
                    models.CharField(
                        choices=[(b"at_risk", b"At Risk"), (b"safe", b"Safe")],
                        max_length=7,
                    ),
                ),
                ("reason", models.TextField(max_length=500)),
                ("communication", models.BooleanField(default=False)),
                (
                    "describe_communication",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "additional_comments",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "observed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "observer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date_added"],
            },
        ),
    ]
