# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sbo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sbo",
            name="behavior_type",
            field=models.CharField(choices=[("at_risk", "At Risk"), ("safe", "Safe")], max_length=7),
        ),
        migrations.AlterField(
            model_name="sbo",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Added"),
        ),
        migrations.AlterField(
            model_name="sbo",
            name="date_observed",
            field=models.DateTimeField(verbose_name="Date Observed"),
        ),
    ]
