# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, b"Job Created"),
                            (2, b"Job Saved"),
                            (12, b"Deleted Log"),
                            (4, b"Item Saved"),
                            (3, b"Item Added"),
                            (5, b"Item Deleted"),
                            (14, b"Approved"),
                            (15, b"Filed Out"),
                            (16, b"Proofed"),
                            (17, b"Nine Digit Added"),
                            (25, b"Item Forecast"),
                            (26, b"Item Preflight"),
                            (18, b"Item Rejected"),
                            (6, b"Production Edited"),
                            (13, b"Revision"),
                            (10, b"Billing"),
                            (7, b"Note"),
                            (8, b"JDF Action"),
                            (9, b"JDF Error"),
                            (11, b"Fedex"),
                            (19, b"Critical Info"),
                            (20, b"FTP Action"),
                            (22, b"Warning"),
                            (21, b"Error"),
                            (23, b"QC Submitted"),
                            (24, b"Review QC Submitted"),
                        ]
                    ),
                ),
                ("log_text", models.TextField()),
                ("is_editable", models.BooleanField(default=True)),
                (
                    "event_time",
                    models.DateTimeField(auto_now_add=True, verbose_name=b"Date"),
                ),
            ],
            options={
                "verbose_name": "Job Log",
                "verbose_name_plural": "Job Logs",
            },
        ),
    ]
