# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("joblog", "0002_auto_20180302_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblog",
            name="event_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="joblog",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Job Created"),
                    (2, "Job Saved"),
                    (12, "Deleted Log"),
                    (4, "Item Saved"),
                    (3, "Item Added"),
                    (5, "Item Deleted"),
                    (14, "Approved"),
                    (15, "Filed Out"),
                    (16, "Proofed"),
                    (17, "Nine Digit Added"),
                    (25, "Item Forecast"),
                    (26, "Item Preflight"),
                    (18, "Item Rejected"),
                    (6, "Production Edited"),
                    (13, "Revision"),
                    (10, "Billing"),
                    (7, "Note"),
                    (8, "JDF Action"),
                    (9, "JDF Error"),
                    (11, "Fedex"),
                    (19, "Critical Info"),
                    (20, "FTP Action"),
                    (22, "Warning"),
                    (21, "Error"),
                    (23, "QC Submitted"),
                    (24, "Review QC Submitted"),
                ]
            ),
        ),
    ]
