# Generated by Django 5.2.5 on 2025-08-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("joblog", "0005_auto_20220531_1104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
