# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("address1", models.CharField(max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(blank=True, max_length=255)),
                ("zip_code", models.CharField(max_length=255)),
                ("country", models.CharField(default=b"US", max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("ext", models.CharField(blank=True, max_length=25)),
                ("fax", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("active", models.BooleanField(default=1)),
            ],
            options={
                "ordering": ["last_name"],
            },
        ),
    ]
