"""
Country conversion table. Also note that the generated COUNTRY_CHOICES_LIST can
be used for any valid choices field thing.

Note that while this is an extremely poopy, sloppy solution, we need it to
massage some of the junk we get that comes in from ETools. They are doing no
validation whatsoever, so we get all kinds of whacky stuff that people can
manually enter into Text fields.
"""

# A dict full of countries and their 2-character abbreviated form that
# FedEx recognizes. FedEx has no way to convert a full name to the 2-char
# form right now.
country_dict = {
    "AFGHANISTAN": "AF",
    "ALBANIA": "AL",
    "ALGERIA": "DZ",
    "ANDORRA": "AD",
    "ANGOLA": "AO",
    "ANGUILLA": "AI",
    "ANTARCTICA": "AQ",
    "ANTIGUA AND BARBUDA": "AG",
    "ARGENTINA REPUBLIC": "AR",
    "ARMENIA": "AM",
    "ARUBA": "AW",
    "AUSTRALIA": "AU",
    "AUSTRIA": "AT",
    "AZERBAIJAN": "AZ",
    "BAHAMAS": "BS",
    "BAHRAIN": "BH",
    "BANGLADESH": "BD",
    "BARBADOS": "BB",
    "BELARUS": "BY",
    "BELGIUM": "BE",
    "BELIZE": "BZ",
    "BENIN": "BJ",
    "BERMUDA": "BM",
    "BHUTAN": "BT",
    "BOLIVIA": "BO",
    "BOSNIA-HERZEGOVINA": "BA",
    "BOTSWANA": "BW",
    "BOUVET ISLAND": "BV",
    "BRAZIL": "BR",
    "BRITISH INDIAN OCEAN TERR": "IO",
    "BRITISH VIRGIN ISLANDS": "VG",
    "BRUNEI DARUSSALAM": "BN",
    "BULGARIA": "BG",
    "BURKINA FASO": "BF",
    "BURUNDI": "BI",
    "CAMBODIA": "KH",
    "CAMEROON": "CM",
    "CANADA": "CA",
    "CAPE VERDE": "CV",
    "CAYMAN ISLANDS": "KY",
    "CENTRAL AFRICAN REPUBLIC": "CF",
    "CHAD": "TD",
    "CHILE": "CL",
    "CHINA": "CN",
    "CHRISTMAS ISLANDS": "CX",
    "COCOS ISLANDS": "CC",
    "COLOMBIA": "CO",
    "COMORAS": "KM",
    "CONGO": "CG",
    "COOK ISLANDS": "CK",
    "COSTA RICA": "CR",
    "COTE D IVOIRE": "CI",
    "CROATIA": "HR",
    "CUBA": "CU",
    "CYPRUS": "CY",
    "CZECH REPUBLIC": "CZ",
    "DENMARK": "DK",
    "DJIBOUTI": "DJ",
    "DOMINICA": "DM",
    "DOMINICAN REPUBLIC": "DO",
    "EAST TIMOR": "TP",
    "ECUADOR": "EC",
    "EGYPT": "EG",
    "EL SALVADOR": "SV",
    "EQUATORIAL GUINEA": "GQ",
    "ESTONIA": "EE",
    "ETHIOPIA": "ET",
    "FALKLAND ISLANDS": "FK",
    "FAROE ISLANDS": "FO",
    "FIJI": "FJ",
    "FINLAND": "FI",
    "FRANCE": "FR",
    "FRANCE METROPOLITAN": "FX",
    "FRENCH GUIANA": "GF",
    "FRENCH POLYNESIA": "PF",
    "FRENCH SOUTHERN TERRITORIES": "TF",
    "GABON": "GA",
    "GAMBIA": "GM",
    "GEORGIA": "GE",
    "GERMANY": "DE",
    "GHANA": "GH",
    "GIBRALTER": "GI",
    "GREECE": "GR",
    "GREENLAND": "GL",
    "GRENADA": "GD",
    "GUADELOUPE": "GP",
    "GUAM": "GU",
    "GUATEMALA": "GT",
    "GUINEA": "GN",
    "GUINEA-BISSAU": "GW",
    "GUYANA": "GY",
    "HAITI": "HT",
    "HEARD & MCDONALD ISLAND": "HM",
    "HONDURAS": "HN",
    "HONG KONG": "HK",
    "HUNGARY": "HU",
    "ICELAND": "IS",
    "INDIA": "IN",
    "INDONESIA": "ID",
    "IRAN, ISLAMIC REPUBLIC OF": "IR",
    "IRAQ": "IQ",
    "IRELAND": "IE",
    "ISRAEL": "IL",
    "ITALY": "IT",
    "JAMAICA": "JM",
    "JAPAN": "JP",
    "JORDAN": "JO",
    "KAZAKHSTAN": "KZ",
    "KENYA": "KE",
    "KIRIBATI": "KI",
    "KOREA, DEM. PEOPLES REP OF": "KP",
    "KOREA, REPUBLIC OF": "KR",
    "KUWAIT": "KW",
    "KYRGYZSTAN": "KG",
    "LAO PEOPLE'S DEM. REPUBLIC": "LA",
    "LATVIA": "LV",
    "LEBANON": "LB",
    "LESOTHO": "LS",
    "LIBERIA": "LR",
    "LIBYAN ARAB JAMAHIRIYA": "LY",
    "LIECHTENSTEIN": "LI",
    "LITHUANIA": "LT",
    "LUXEMBOURG": "LU",
    "MACAO": "MO",
    "MACEDONIA": "MK",
    "MADAGASCAR": "MG",
    "MALAWI": "MW",
    "MALAYSIA": "MY",
    "MALDIVES": "MV",
    "MALI": "ML",
    "MALTA": "MT",
    "MARSHALL ISLANDS": "MH",
    "MARTINIQUE": "MQ",
    "MAURITANIA": "MR",
    "MAURITIUS": "MU",
    "MAYOTTE": "YT",
    "MEXICO": "MX",
    "MICRONESIA": "FM",
    "MOLDAVA REPUBLIC OF": "MD",
    "MONACO": "MC",
    "MONGOLIA": "MN",
    "MONTENEGRO": "ME",
    "MONTSERRAT": "MS",
    "MOROCCO": "MA",
    "MOZAMBIQUE": "MZ",
    "MYANMAR": "MM",
    "NAMIBIA": "NA",
    "NAURU": "NR",
    "NEPAL": "NP",
    "NETHERLANDS ANTILLES": "AN",
    "NETHERLANDS": "NL",
    "NEW CALEDONIA": "NC",
    "NEW ZEALAND": "NZ",
    "NICARAGUA": "NI",
    "NIGER": "NE",
    "NIGERIA": "NG",
    "NIUE": "NU",
    "NORFOLK ISLAND": "NF",
    "NORTHERN MARIANA ISLANDS": "MP",
    "NORWAY": "NO",
    "OMAN": "OM",
    "PAKISTAN": "PK",
    "PALAU": "PW",
    "PANAMA": "PA",
    "PAPUA NEW GUINEA": "PG",
    "PARAGUAY": "PY",
    "PERU": "PE",
    "PHILLIPINES": "PH",
    "PITCAIRN": "PN",
    "POLAND": "PL",
    "PORTUGAL": "PT",
    "PUERTO RICO": "PR",
    "QATAR": "QA",
    "REUNION": "RE",
    "ROMANIA": "RO",
    "RUSSIAN FEDERATION": "RU",
    "RWANDA": "RW",
    "SAMOA": "WS",
    "SAN MARINO": "SM",
    "SAO TOME/PRINCIPE": "ST",
    "SAUDI ARABIA": "SA",
    "SENEGAL": "SN",
    "SERBIA": "SP",
    "SEYCHELLES": "SC",
    "SIERRA LEONE": "SL",
    "SINGAPORE": "SG",
    "SLOVAKIA": "SK",
    "SLOVENIA": "SI",
    "SOLOMON ISLANDS": "SB",
    "SOMALIA": "SO",
    "SOMOA,GILBERT,ELLICE ISLANDS": "AS",
    "SOUTH AFRICA": "ZA",
    "SPAIN": "ES",
    "SRI LANKA": "LK",
    "ST. HELENA": "SH",
    "ST. KITTS AND NEVIS": "KN",
    "ST. LUCIA": "LC",
    "ST. PIERRE AND MIQUELON": "PM",
    "ST. VINCENT & THE GRENADINES": "VC",
    "SUDAN": "SD",
    "SURINAME": "SR",
    "SVALBARD AND JAN MAYEN": "SJ",
    "SWAZILAND": "SZ",
    "SWEDEN": "SE",
    "SWITZERLAND": "CH",
    "SYRIAN ARAB REPUBLIC": "SY",
    "TAIWAN": "TW",
    "TAJIKISTAN": "TJ",
    "TANZANIA, UNITED REPUBLIC OF": "TZ",
    "THAILAND": "TH",
    "TOGO": "TG",
    "TOKELAU": "TK",
    "TONGA": "TO",
    "TRINIDAD AND TOBAGO": "TT",
    "TUNISIA": "TN",
    "TURKEY": "TR",
    "TURKMENISTAN": "TM",
    "TURKS AND CALCOS ISLANDS": "TC",
    "TUVALU": "TV",
    "UGANDA": "UG",
    "UKRAINE": "UA",
    "UNITED ARAB EMIRATES": "AE",
    "UNITED KINGDOM": "GB",
    "DOMESTIC": "US",
    "USA": "US",
    "US": "US",
    "U.S.A.": "US",
    "U.S.": "US",
    "UNITED": "US",
    "UNITED STATES": "US",
    "UNITED STATES MINOR OUTL.IS.": "UM",
    "URUGUAY": "UY",
    "UZBEKISTAN": "UZ",
    "VANUATU": "VU",
    "VATICAN CITY STATE": "VA",
    "VENEZUELA": "VE",
    "VIET NAM": "VN",
    "VIRGIN ISLANDS (USA)": "VI",
    "WALLIS AND FUTUNA ISLANDS": "WF",
    "WESTERN SAHARA": "EH",
    "YEMEN": "YE",
    "YUGOSLAVIA": "YU",
    "ZAIRE": "ZR",
    "ZAMBIA": "ZM",
    "ZIMBABWE": "ZW",
}


def full_to_abbrev(full_name):
    """
    Returns the abbreviation for a country, given its full name. Default to US
    when no match can be found.
    """
    if len(full_name) == 2:
        # It's already abbreviated.
        return full_name

    return country_dict.get(full_name.upper(), "US")


# This dict holds the full names of each country's states, along with their
# shortened, 2-character form that FedEx recognizes. Sucks we have to do this,
# but there is currently no FedEx solution to do it for us.
state_dict = {
    # Canada
    "CA": {
        "ALBERTA": "AB",
        "BRITISH COLUMBIA": "BC",
        "Manitoba": "MB",
        "NEW BRUNSWICK": "NB",
        "NEWFOUNDLAND": "NL",
        "NORTHWEST TERRITORIES": "NT",
        "NOVA SCOTIA": "NS",
        "NUNAVUT": "NU",
        "ONTARIO": "ON",
        "PRINCE EDWARD ISLAND": "PE",
        "QUEBEC": "QC",
        "SASKATCHEWAN": "SK",
        "YUKON": "YT",
    },
    # Mexico
    "MX": {
        "AGUASCALIENTES": "AG",
        "BAJA CALIFORNIA NORTE": "BC",
        "BAJA CALIFORNIA SUR": "BS",
        "CAMPECHE": "CM",
        "CHIAPAS": "CS",
        "CHIHUAHUA": "CH",
        "COAHUILA": "CO",
        "COLIMA": "CL",
        "DISTRITO FEDERAL": "DF",
        "DURANGO": "DG",
        "GUANAJUATO": "GT",
        "GUERRERO": "GR",
        "HIDALGO": "HG",
        "JALISCO": "JA",
        "MEXICO": "MX",
        "MICHOACAN": "MI",
        "MORELOS": "MO",
        "NAYARIT": "NA",
        "NUEVO LEON": "NL",
        "OAXACA": "OA",
        "PUEBLA": "PU",
        "QUERETARO": "QT",
        "QUINTANA ROO": "QR",
        "SAN LUIS POTOSI": "SL",
        "SINALOA": "SI",
        "SONORA": "SO",
        "TABASCO": "TB",
        "TAMAULIPAS": "TM",
        "TLAXCALA": "TL",
        "VERACRUZ": "VE",
        "YUCATAN": "YU",
        "ZACATECAS": "ZA",
    },
}


def country_state_to_abbrev(country, state):
    """
    Given a country name or abbreviation and the full spelled out name of one
    of its states, return a shortened state/province code that FedEx
    recognizes.
    """
    abbr_country = full_to_abbrev(country)
    try:
        return state_dict[abbr_country][state.upper()]
    except KeyError:
        return state
