# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutoFTPTiff",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.IntegerField(choices=[(6, b"Fusion_Flexo"), (11, b"Cyber_Graphics")]),
                ),
                (
                    "date_queued",
                    models.DateTimeField(auto_now_add=True, verbose_name=b"Date Queued"),
                ),
                (
                    "date_processed",
                    models.DateTimeField(blank=True, null=True, verbose_name=b"Date Processed"),
                ),
            ],
            options={
                "ordering": ["-date_queued"],
            },
        ),
    ]
