# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auto_ftp", "0001_initial"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoftptiff",
            name="items",
            field=models.ManyToManyField(to="workflow.Item"),
        ),
        migrations.AddField(
            model_name="autoftptiff",
            name="job",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="workflow.Job"),
        ),
    ]
