# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_ftp", "0002_auto_20180302_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoftptiff",
            name="destination",
            field=models.IntegerField(
                choices=[
                    (6, b"Fusion_Flexo"),
                    (11, b"Cyber_Graphics"),
                    (16, b"Southern_Graphic"),
                    (21, b"Phototype"),
                ]
            ),
        ),
    ]
