# Generated by Django 2.2 on 2020-02-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_ftp", "0003_auto_20191121_0934"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoftptiff",
            name="date_processed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date Processed"
            ),
        ),
        migrations.AlterField(
            model_name="autoftptiff",
            name="date_queued",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Queued"),
        ),
        migrations.AlterField(
            model_name="autoftptiff",
            name="destination",
            field=models.IntegerField(
                choices=[
                    (6, "Fusion_Flexo"),
                    (11, "Cyber_Graphics"),
                    (16, "Southern_Graphic"),
                    (21, "Phototype"),
                ]
            ),
        ),
    ]
