# Generated by Django 5.2.5 on 2025-08-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_ftp", "0004_auto_20200208_1021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoftptiff",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
