# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("January", models.IntegerField()),
                ("February", models.IntegerField()),
                ("March", models.IntegerField()),
                ("April", models.IntegerField()),
                ("May", models.IntegerField()),
                ("June", models.IntegerField()),
                ("July", models.IntegerField()),
                ("August", models.IntegerField()),
                ("September", models.IntegerField()),
                ("October", models.IntegerField()),
                ("November", models.IntegerField()),
                ("December", models.IntegerField()),
                (
                    "workflow",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sites.Site"),
                ),
            ],
            options={
                "verbose_name_plural": "Budget",
            },
        ),
        migrations.CreateModel(
            name="InvoiceAmt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("January", models.IntegerField(blank=True, null=True)),
                ("February", models.IntegerField(blank=True, null=True)),
                ("March", models.IntegerField(blank=True, null=True)),
                ("April", models.IntegerField(blank=True, null=True)),
                ("May", models.IntegerField(blank=True, null=True)),
                ("June", models.IntegerField(blank=True, null=True)),
                ("July", models.IntegerField(blank=True, null=True)),
                ("August", models.IntegerField(blank=True, null=True)),
                ("September", models.IntegerField(blank=True, null=True)),
                ("October", models.IntegerField(blank=True, null=True)),
                ("November", models.IntegerField(blank=True, null=True)),
                ("December", models.IntegerField(blank=True, null=True)),
                (
                    "budget",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="budget.Budget"),
                ),
            ],
            options={
                "verbose_name_plural": "Invoice Amounts",
            },
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together=set([("year", "workflow")]),
        ),
    ]
