# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change",
                    models.TextField(
                        help_text=b"A description of the change, in terms that the end users can understand."
                    ),
                ),
                (
                    "change_type",
                    models.IntegerField(
                        choices=[
                            (0, b"Feature Enhancement"),
                            (1, b"New Feature"),
                            (1, b"Bug Fix"),
                        ]
                    ),
                ),
                (
                    "impact_level",
                    models.IntegerField(
                        choices=[(0, b"Low"), (1, b"Medium"), (2, b"High")],
                        help_text=b"How big or important of a change this is.",
                    ),
                ),
                (
                    "cool_points",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, b"1"),
                            (2, b"2"),
                            (3, b"3"),
                            (4, b"4"),
                            (5, b"5"),
                            (6, b"6"),
                            (7, b"7"),
                            (8, b"8"),
                            (9, b"9"),
                            (10, b"10"),
                        ],
                        default=5,
                        help_text=b"How cool this change is.",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        help_text=b"The post date. May be changed to affect sorting.",
                    ),
                ),
                ("growl_date", models.DateTimeField(blank=True, null=True)),
                (
                    "workflows_affected",
                    models.ManyToManyField(
                        help_text=b"Which workflows are affected by the change.",
                        to="sites.Site",
                    ),
                ),
            ],
        ),
    ]
