# Generated by Django 2.2 on 2019-09-23 11:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codechange",
            name="change",
            field=models.TextField(
                help_text="A description of the change, in terms that the end users can understand."
            ),
        ),
        migrations.AlterField(
            model_name="codechange",
            name="change_type",
            field=models.IntegerField(
                choices=[(0, "Feature Enhancement"), (1, "New Feature"), (1, "Bug Fix")]
            ),
        ),
        migrations.AlterField(
            model_name="codechange",
            name="cool_points",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                default=5,
                help_text="How cool this change is.",
            ),
        ),
        migrations.AlterField(
            model_name="codechange",
            name="creation_date",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                help_text="The post date. May be changed to affect sorting.",
            ),
        ),
        migrations.AlterField(
            model_name="codechange",
            name="impact_level",
            field=models.IntegerField(
                choices=[(0, "Low"), (1, "Medium"), (2, "High")],
                help_text="How big or important of a change this is.",
            ),
        ),
        migrations.AlterField(
            model_name="codechange",
            name="workflows_affected",
            field=models.ManyToManyField(
                help_text="Which workflows are affected by the change.", to="sites.Site"
            ),
        ),
    ]
