# Generated by Django 5.2.5 on 2025-08-31 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_codechange_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codechange",
            name="creation_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The post date. May be changed to affect sorting.",
            ),
        ),
    ]
