services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DEV_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DEV_DB_NAME:-gchub_dev}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: gchub_dev_pgdata
