# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QAD_CasePacks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_pack", models.IntegerField()),
            ],
            options={
                "verbose_name": "QAD Case Pack",
                "verbose_name_plural": "QAD Case Packs",
            },
        ),
        migrations.CreateModel(
            name="QAD_PrintGroups",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "QAD Print Group",
                "verbose_name_plural": "QAD Print Groups",
            },
        ),
    ]
