# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qad_data", "0002_qad_casepacks_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="qad_casepacks",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
