# Generated by Django 5.2.5 on 2025-08-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qad_data", "0003_qad_casepacks_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qad_casepacks",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="qad_printgroups",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
