# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_id", models.PositiveIntegerField()),
                ("tracking_num", models.CharField(blank=True, max_length=15)),
                ("date_shipped", models.DateTimeField(auto_now_add=True)),
                ("date_label_printed", models.DateTimeField(blank=True, null=True)),
                (
                    "ship_carrier_code",
                    models.CharField(
                        choices=[
                            (b"FDXE", b"FedEx Express"),
                            (b"FDXG", b"FedEx Ground"),
                            (b"FDXC", b"FedEx Cargo"),
                            (b"FXCC", b"FedEx Custom Critical"),
                            (b"FXFR", b"FedEx Freight"),
                        ],
                        default=b"FDXE",
                        max_length=15,
                    ),
                ),
                (
                    "ship_packaging",
                    models.CharField(
                        choices=[
                            (b"FEDEX_ENVELOPE", b"FedEx Envelope"),
                            (b"FEDEX_PAK", b"FedEx Pak"),
                            (b"FEDEX_BOX", b"FedEx Box"),
                            (b"FEDEX_TUBE", b"FedEx Tube"),
                            (b"FEDEX_10KG_BOX", b"FedEx 10 kg Box"),
                            (b"FEDEX_25KG_BOX", b"FedEx 25 kg Box"),
                            (b"YOUR_PACKAGING", b"Packaging Supplied"),
                        ],
                        default=b"FEDEX_PAK",
                        max_length=50,
                    ),
                ),
                ("ship_weight", models.FloatField(default=1.0)),
                (
                    "ship_service",
                    models.CharField(
                        choices=[
                            (b"PRIORITY_OVERNIGHT", b"Priority Overnight"),
                            (b"STANDARD_OVERNIGHT", b"Standard Overnight"),
                            (b"FIRST_OVERNIGHT", b"First Overnight"),
                            (b"FEDEX_2_DAY", b"FedEx Two Day"),
                            (b"FEDEX_EXPRESS_SAVER", b"FedEx Express Saver"),
                            (b"INTERNATIONAL_PRIORITY", b"International - Priority"),
                            (b"INTERNATIONAL_ECONOMY", b"International - Economy"),
                            (b"INTERNATIONAL_FIRST", b"International - First Class"),
                            (b"FEDEX_GROUND", b"FedEx Ground"),
                            (b"GROUND_HOME_DELIVERY", b"Ground Home Delivery"),
                            (
                                b"EUROPE_FIRST_INTERNATIONAL_PRIORITY",
                                b"Europe - First International Priority",
                            ),
                        ],
                        default=b"PRIORITY_OVERNIGHT",
                        max_length=75,
                    ),
                ),
                ("label_data", models.TextField(blank=True, null=True)),
                ("net_shipping_cost", models.FloatField(blank=True, null=True)),
                (
                    "address_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
        ),
    ]
