# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fedexsys", "0002_shipment_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="ship_carrier_code",
            field=models.CharField(
                choices=[
                    ("FDXE", "FedEx Express"),
                    ("FDXG", "FedEx Ground"),
                    ("FDXC", "FedEx Cargo"),
                    ("FXCC", "FedEx Custom Critical"),
                    ("FXFR", "FedEx Freight"),
                ],
                default="FDXE",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="ship_packaging",
            field=models.CharField(
                choices=[
                    ("FEDEX_ENVELOPE", "FedEx Envelope"),
                    ("FEDEX_PAK", "FedEx Pak"),
                    ("FEDEX_BOX", "FedEx Box"),
                    ("FEDEX_TUBE", "FedEx Tube"),
                    ("FEDEX_10KG_BOX", "FedEx 10 kg Box"),
                    ("FEDEX_25KG_BOX", "FedEx 25 kg Box"),
                    ("YOUR_PACKAGING", "Packaging Supplied"),
                ],
                default="FEDEX_PAK",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="ship_service",
            field=models.CharField(
                choices=[
                    ("PRIORITY_OVERNIGHT", "Priority Overnight"),
                    ("STANDARD_OVERNIGHT", "Standard Overnight"),
                    ("FIRST_OVERNIGHT", "First Overnight"),
                    ("FEDEX_2_DAY", "FedEx Two Day"),
                    ("FEDEX_EXPRESS_SAVER", "FedEx Express Saver"),
                    ("INTERNATIONAL_PRIORITY", "International - Priority"),
                    ("INTERNATIONAL_ECONOMY", "International - Economy"),
                    ("INTERNATIONAL_FIRST", "International - First Class"),
                    ("FEDEX_GROUND", "FedEx Ground"),
                    ("GROUND_HOME_DELIVERY", "Ground Home Delivery"),
                    (
                        "EUROPE_FIRST_INTERNATIONAL_PRIORITY",
                        "Europe - First International Priority",
                    ),
                ],
                default="PRIORITY_OVERNIGHT",
                max_length=75,
            ),
        ),
    ]
