# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Software",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_name", models.CharField(max_length=255)),
                ("serial_number", models.CharField(blank=True, max_length=255)),
                ("version", models.CharField(blank=True, max_length=255)),
                ("vendor", models.CharField(blank=True, max_length=255)),
                ("os", models.CharField(blank=True, max_length=255)),
                ("installation_location", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["application_name"],
                "verbose_name_plural": "Software",
            },
        ),
    ]
