# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drawdown",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("job_number", models.IntegerField(blank=True, null=True)),
                ("substrate", models.CharField(max_length=255)),
                ("colors_needed", models.CharField(max_length=255)),
                ("number_copies", models.IntegerField(blank=True, null=True)),
                ("send_prints_to", models.TextField(max_length=255)),
                ("comments", models.TextField(blank=True, max_length=500)),
                (
                    "date_needed",
                    models.DateField(
                        blank=True, null=True, verbose_name=b"Date Needed"
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name=b"Date Created"
                    ),
                ),
                ("request_complete", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["customer_name"],
            },
        ),
    ]
