# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 14:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0003_auto_20180601_1533"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("draw_down", "0002_auto_20180302_1702"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawDownItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.IntegerField(blank=True, null=True)),
                ("substrate", models.CharField(max_length=255)),
                ("colors_needed", models.CharField(max_length=255)),
                ("number_copies", models.IntegerField(blank=True, null=True)),
                ("artwork", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["item_number"],
            },
        ),
        migrations.CreateModel(
            name="DrawDownRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("send_prints_to", models.TextField(max_length=255)),
                ("comments", models.TextField(blank=True, max_length=500)),
                (
                    "date_needed",
                    models.DateField(blank=True, null=True, verbose_name=b"Date Needed"),
                ),
                (
                    "creation_date",
                    models.DateField(blank=True, null=True, verbose_name=b"Date Created"),
                ),
                ("request_complete", models.BooleanField(default=False)),
                ("job_number", models.IntegerField(blank=True, null=True)),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["customer_name"],
            },
        ),
        migrations.AddField(
            model_name="drawdownitem",
            name="draw_down_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="draw_down.DrawDownRequest",
            ),
        ),
        migrations.AddField(
            model_name="drawdownitem",
            name="print_location",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="workflow.PrintLocation"),
        ),
    ]
