# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 16:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("draw_down", "0003_auto_20180905_1430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawdownitem",
            name="draw_down_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="draw_down.DrawDownRequest",
            ),
        ),
    ]
