# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("draw_down", "0004_auto_20180907_1601"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawdown",
            name="creation_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date Created"),
        ),
        migrations.AlterField(
            model_name="drawdown",
            name="date_needed",
            field=models.DateField(blank=True, null=True, verbose_name="Date Needed"),
        ),
        migrations.AlterField(
            model_name="drawdownrequest",
            name="creation_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date Created"),
        ),
        migrations.AlterField(
            model_name="drawdownrequest",
            name="date_needed",
            field=models.DateField(blank=True, null=True, verbose_name="Date Needed"),
        ),
    ]
