# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BevInvoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=50, verbose_name=b"Invoice No."),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name=b"Date Created"),
                ),
                (
                    "qad_entry_date",
                    models.DateField(blank=True, null=True, verbose_name=b"QAD Entry Date"),
                ),
                (
                    "invoice_entry_date",
                    models.DateField(blank=True, null=True, verbose_name=b"Invoice Date"),
                ),
                (
                    "pdf_sent_date",
                    models.DateField(blank=True, null=True, verbose_name=b"PDF Send Date"),
                ),
                (
                    "invoice_entry_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_entered_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
