# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflow", "0001_initial"),
        ("bev_billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bevinvoice",
            name="job",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="workflow.Job"),
        ),
        migrations.AddField(
            model_name="bevinvoice",
            name="qad_entry_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qad_entered_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
