# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bev_billing", "0002_auto_20180302_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bevinvoice",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Created"),
        ),
        migrations.AlterField(
            model_name="bevinvoice",
            name="invoice_entry_date",
            field=models.DateField(blank=True, null=True, verbose_name="Invoice Date"),
        ),
        migrations.AlterField(
            model_name="bevinvoice",
            name="invoice_number",
            field=models.CharField(max_length=50, verbose_name="Invoice No."),
        ),
        migrations.AlterField(
            model_name="bevinvoice",
            name="pdf_sent_date",
            field=models.DateField(blank=True, null=True, verbose_name="PDF Send Date"),
        ),
        migrations.AlterField(
            model_name="bevinvoice",
            name="qad_entry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="QAD Entry Date"
            ),
        ),
    ]
