# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ColorDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                ("lab_l", models.FloatField(blank=True, null=True)),
                ("lab_a", models.FloatField(blank=True, null=True)),
                ("lab_b", models.FloatField(blank=True, null=True)),
                ("lch_c", models.FloatField(blank=True, null=True)),
                ("lch_h", models.FloatField(blank=True, null=True)),
                (
                    "coating",
                    models.CharField(
                        choices=[
                            (b"C", b"Coated"),
                            (b"U", b"Uncoated"),
                            (b"O", b"Other"),
                        ],
                        max_length=1,
                    ),
                ),
                ("hexvalue", models.CharField(blank=True, max_length=12)),
                ("do_compare", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="colordefinition",
            unique_together=set([("name", "coating")]),
        ),
    ]
