# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("color_mgt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colordefinition",
            name="coating",
            field=models.CharField(
                choices=[("C", "Coated"), ("U", "Uncoated"), ("O", "Other")],
                max_length=1,
            ),
        ),
    ]
