# Generated by Django 2.2 on 2021-07-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("color_mgt", "0002_auto_20190923_1111"),
    ]

    operations = [
        migrations.AddField(
            model_name="colordefinition",
            name="pantone_plus",
            field=models.BooleanField(default=False),
        ),
    ]
