# Generated by Django 5.2.5 on 2025-08-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("color_mgt", "0003_colordefinition_pantone_plus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colordefinition",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
