# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QCCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField()),
            ],
            options={
                "ordering": ["order"],
                "verbose_name": "QC Category",
                "verbose_name_plural": "QC Categories",
            },
        ),
        migrations.CreateModel(
            name="QCQuestionDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("help_url", models.URLField(blank=True, null=True)),
                ("order", models.IntegerField()),
            ],
            options={
                "ordering": ["workflow", "category", "order"],
                "verbose_name": "QC Question Definition",
                "verbose_name_plural": "QC Question Definitions",
            },
        ),
        migrations.CreateModel(
            name="QCResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response",
                    models.IntegerField(
                        choices=[
                            (0, b"No Response"),
                            (1, b"OK"),
                            (2, b"Whoops!"),
                            (3, b"N/A"),
                        ],
                        default=0,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("artist_notified", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["id"],
                "verbose_name": "QC Response",
                "verbose_name_plural": "QC Responses",
            },
        ),
        migrations.CreateModel(
            name="QCResponseDoc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-review_date"],
                "verbose_name": "QC Reponse Document",
                "verbose_name_plural": "QC Reponse Documents",
            },
        ),
        migrations.CreateModel(
            name="QCWhoops",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.TextField()),
                ("is_valid", models.BooleanField(default=True)),
                ("reported_date", models.DateTimeField(auto_now_add=True)),
                ("artist_comments", models.TextField(blank=True, null=True)),
                ("resolution_date", models.DateTimeField(blank=True, null=True)),
                (
                    "qc_response",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="qc.QCResponse"),
                ),
            ],
            options={
                "ordering": ["id"],
                "verbose_name": "Whoops!",
                "verbose_name_plural": "Whoopsies!",
            },
        ),
    ]
