# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("qc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflow", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="qcresponsedoc",
            name="items",
            field=models.ManyToManyField(editable=False, to="workflow.Item"),
        ),
        migrations.AddField(
            model_name="qcresponsedoc",
            name="job",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.Job",
            ),
        ),
        migrations.AddField(
            model_name="qcresponsedoc",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qc.QCResponseDoc",
            ),
        ),
        migrations.AddField(
            model_name="qcresponsedoc",
            name="reviewer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="qcresponse",
            name="category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="qc.QCCategory"),
        ),
        migrations.AddField(
            model_name="qcresponse",
            name="qcdoc",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="qc.QCResponseDoc"),
        ),
        migrations.AddField(
            model_name="qcquestiondefinition",
            name="category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="qc.QCCategory"),
        ),
        migrations.AddField(
            model_name="qcquestiondefinition",
            name="workflow",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sites.Site"),
        ),
    ]
