# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qc", "0002_auto_20180302_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qcresponse",
            name="response",
            field=models.IntegerField(
                choices=[(0, "No Response"), (1, "OK"), (2, "Whoops!"), (3, "N/A")],
                default=0,
            ),
        ),
    ]
