# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0008_alter_user_username_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (b"VA", b"Vacation - Full Day"),
                            (b"HV", b"Vacation - Half Day"),
                            (b"OV", b"Office Visit"),
                            (b"OM", b"Office Meeting"),
                            (b"BT", b"Business Trip"),
                            (b"SD", b"Sick Day"),
                            (b"SH", b"Sick Half-Day"),
                            (b"HO", b"Holiday"),
                            (b"LA", b"Leave of Absence"),
                            (b"DA", b"Doctor Appt."),
                            (b"OO", b"Out of Office"),
                        ],
                        max_length=2,
                    ),
                ),
                ("event_date", models.DateField(verbose_name=b"Event Date")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("limit_to_group", models.ManyToManyField(blank=True, to="auth.Group")),
            ],
            options={
                "ordering": ["-date_added"],
            },
        ),
    ]
