# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(verbose_name="Event Date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("VA", "Vacation - Full Day"),
                    ("HV", "Vacation - Half Day"),
                    ("OV", "Office Visit"),
                    ("OM", "Office Meeting"),
                    ("BT", "Business Trip"),
                    ("SD", "Sick Day"),
                    ("SH", "Sick Half-Day"),
                    ("HO", "Holiday"),
                    ("LA", "Leave of Absence"),
                    ("DA", "Doctor Appt."),
                    ("OO", "Out of Office"),
                ],
                max_length=2,
            ),
        ),
    ]
