# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Error",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reported_date",
                    models.DateTimeField(auto_now_add=True, verbose_name=b"Error Date"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            (b"1", b"Prepress"),
                            (b"2", b"Films"),
                            (b"3", b"Plates"),
                            (b"4", b"Press"),
                            (b"5", b"Forming"),
                            (b"6", b"Shipped"),
                        ],
                        max_length=4,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
