# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("error_tracking", "0002_auto_20180302_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="error",
            name="reported_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Error Date"),
        ),
        migrations.AlterField(
            model_name="error",
            name="stage",
            field=models.CharField(
                choices=[
                    ("1", "Prepress"),
                    ("2", "Films"),
                    ("3", "Plates"),
                    ("4", "Press"),
                    ("5", "Forming"),
                    ("6", "Shipped"),
                ],
                max_length=4,
            ),
        ),
    ]
