# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionalInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keep_same_upc", models.BooleanField(default=False)),
                ("replaces_prev_design", models.BooleanField(default=False)),
                (
                    "prev_9_digit",
                    models.CharField(blank=True, max_length=255, verbose_name=b"Previous 9-Digit #"),
                ),
                (
                    "forecast",
                    models.CharField(
                        choices=[
                            (b"floorstock", b"Floor Stock"),
                            (b"makeandship", b"Make and Ship"),
                            (b"promotional", b"Promotional"),
                        ],
                        max_length=255,
                        verbose_name=b"Forecast",
                    ),
                ),
                (
                    "incoming_art_format",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, b"Digital Art via E-mail"),
                            (2, b"Original Art"),
                            (3, b"Art to be created by Clemson"),
                            (4, b"Recreate from Print Sample"),
                            (5, b"ISDN or FTP"),
                            (6, b"Digital art on Disk"),
                            (9, b"Other"),
                        ],
                        null=True,
                    ),
                ),
                ("arrival_date", models.DateField(blank=True, null=True)),
                ("sender", models.CharField(blank=True, max_length=255)),
                ("date_needed", models.DateField(blank=True, null=True)),
                ("special_instructions", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArtReq",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("design_name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_email", models.CharField(max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            (b"enduser", b"End User"),
                            (b"distributor", b"Distributor"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "print_type",
                    models.CharField(
                        choices=[
                            (b"stock", b"Stock"),
                            (b"local", b"Local"),
                            (b"national", b"National"),
                            (b"trade", b"Trade"),
                            (b"branded", b"Branded"),
                        ],
                        max_length=25,
                    ),
                ),
                ("ship_to_name", models.CharField(max_length=255)),
                ("ship_to_company", models.CharField(blank=True, max_length=255)),
                ("ship_to_addy_1", models.CharField(max_length=255)),
                ("ship_to_addy_2", models.CharField(blank=True, max_length=255)),
                ("ship_to_city", models.CharField(max_length=255)),
                ("ship_to_state", models.CharField(blank=True, max_length=255)),
                ("ship_to_zip", models.CharField(blank=True, max_length=255)),
                ("ship_to_country", models.CharField(blank=True, max_length=255)),
                ("ship_to_email", models.CharField(blank=True, max_length=255)),
                ("ship_to_phone", models.CharField(max_length=255)),
                ("job_num", models.IntegerField(blank=True, null=True)),
                ("corr_job_num", models.IntegerField(blank=True, null=True)),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name=b"test"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtraProof",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ship_to_name",
                    models.CharField(blank=True, max_length=255, verbose_name=b"Name"),
                ),
                (
                    "ship_to_company",
                    models.CharField(blank=True, max_length=255, verbose_name=b"Company"),
                ),
                (
                    "ship_to_addy_1",
                    models.CharField(blank=True, max_length=255, verbose_name=b"Address 1"),
                ),
                (
                    "ship_to_addy_2",
                    models.CharField(blank=True, max_length=255, verbose_name=b"Address 2"),
                ),
                (
                    "ship_to_city",
                    models.CharField(blank=True, max_length=255, verbose_name=b"City"),
                ),
                (
                    "ship_to_state",
                    models.CharField(blank=True, max_length=255, verbose_name=b"State"),
                ),
                (
                    "ship_to_zip",
                    models.CharField(blank=True, max_length=255, verbose_name=b"Zip"),
                ),
                (
                    "ship_to_country",
                    models.CharField(blank=True, max_length=255, verbose_name=b"Country"),
                ),
                (
                    "ship_to_email",
                    models.CharField(blank=True, max_length=255, verbose_name=b"Email"),
                ),
                (
                    "ship_to_phone",
                    models.CharField(blank=True, max_length=255, verbose_name=b"Phone"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketSegment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PartialArtReq",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fieldData", models.TextField(blank=True, null=True)),
                ("fileData", models.TextField(blank=True, null=True)),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name=b"creation"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(blank=True, null=True, verbose_name=b"last_updated"),
                ),
                ("partial_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annual_usage", models.IntegerField(verbose_name=b"Annual Usage")),
                (
                    "order_quantity",
                    models.IntegerField(blank=True, null=True, verbose_name=b"Estimated Order Quantity"),
                ),
                (
                    "customer_number",
                    models.CharField(blank=True, max_length=255, verbose_name=b"Customer Number"),
                ),
                (
                    "wrap_proof",
                    models.BooleanField(default=False, verbose_name=b"Wrap Proof"),
                ),
                (
                    "mock_up",
                    models.BooleanField(default=False, verbose_name=b"Mock-Ups"),
                ),
                ("plant1", models.CharField(blank=True, max_length=255)),
                ("plant2", models.CharField(blank=True, max_length=255)),
                ("plant3", models.CharField(blank=True, max_length=255)),
                ("press1", models.CharField(blank=True, max_length=255)),
                ("press2", models.CharField(blank=True, max_length=255)),
                ("press3", models.CharField(blank=True, max_length=255)),
                (
                    "ship_to_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            (b"AL", "Alabama"),
                            (b"AK", "Alaska"),
                            (b"AS", "American Samoa"),
                            (b"AZ", "Arizona"),
                            (b"AR", "Arkansas"),
                            (b"AA", "Armed Forces Americas"),
                            (b"AE", "Armed Forces Europe"),
                            (b"AP", "Armed Forces Pacific"),
                            (b"CA", "California"),
                            (b"CO", "Colorado"),
                            (b"CT", "Connecticut"),
                            (b"DE", "Delaware"),
                            (b"DC", "District of Columbia"),
                            (b"FL", "Florida"),
                            (b"GA", "Georgia"),
                            (b"GU", "Guam"),
                            (b"HI", "Hawaii"),
                            (b"ID", "Idaho"),
                            (b"IL", "Illinois"),
                            (b"IN", "Indiana"),
                            (b"IA", "Iowa"),
                            (b"KS", "Kansas"),
                            (b"KY", "Kentucky"),
                            (b"LA", "Louisiana"),
                            (b"ME", "Maine"),
                            (b"MD", "Maryland"),
                            (b"MA", "Massachusetts"),
                            (b"MI", "Michigan"),
                            (b"MN", "Minnesota"),
                            (b"MS", "Mississippi"),
                            (b"MO", "Missouri"),
                            (b"MT", "Montana"),
                            (b"NE", "Nebraska"),
                            (b"NV", "Nevada"),
                            (b"NH", "New Hampshire"),
                            (b"NJ", "New Jersey"),
                            (b"NM", "New Mexico"),
                            (b"NY", "New York"),
                            (b"NC", "North Carolina"),
                            (b"ND", "North Dakota"),
                            (b"MP", "Northern Mariana Islands"),
                            (b"OH", "Ohio"),
                            (b"OK", "Oklahoma"),
                            (b"OR", "Oregon"),
                            (b"PA", "Pennsylvania"),
                            (b"PR", "Puerto Rico"),
                            (b"RI", "Rhode Island"),
                            (b"SC", "South Carolina"),
                            (b"SD", "South Dakota"),
                            (b"TN", "Tennessee"),
                            (b"TX", "Texas"),
                            (b"UT", "Utah"),
                            (b"VT", "Vermont"),
                            (b"VI", "Virgin Islands"),
                            (b"VA", "Virginia"),
                            (b"WA", "Washington"),
                            (b"WV", "West Virginia"),
                            (b"WI", "Wisconsin"),
                            (b"WY", "Wyoming"),
                        ],
                        max_length=2,
                        verbose_name=b"Ship to State",
                    ),
                ),
                (
                    "corr_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (b"ipfb", b"IPFB"),
                            (b"gpi", b"GPI"),
                            (b"custom", b"Custom"),
                            (b"preprint", b"Preprint"),
                        ],
                        default=b"gpi",
                        max_length=255,
                        verbose_name=b"Corrugated Type",
                    ),
                ),
                ("corr_only", models.BooleanField(default=False)),
                (
                    "label_color",
                    models.CharField(blank=True, max_length=255, verbose_name=b"Label Color"),
                ),
                (
                    "label_copy_1",
                    models.CharField(blank=True, max_length=22, verbose_name=b"Label Copy 1"),
                ),
                (
                    "label_copy_2",
                    models.CharField(blank=True, max_length=22, verbose_name=b"Label Copy 2"),
                ),
                (
                    "label_copy_3",
                    models.CharField(blank=True, max_length=22, verbose_name=b"Label Copy 3"),
                ),
                ("corr_plant1", models.CharField(blank=True, max_length=255)),
                ("corr_plant2", models.CharField(blank=True, max_length=255)),
                ("corr_plant3", models.CharField(blank=True, max_length=255)),
                (
                    "sleeve_count",
                    models.IntegerField(blank=True, null=True, verbose_name=b"Sleeve Count"),
                ),
                (
                    "print_color",
                    models.CharField(blank=True, max_length=255, verbose_name=b"Print Color"),
                ),
                (
                    "case_color",
                    models.CharField(blank=True, max_length=255, verbose_name=b"Case Color"),
                ),
                (
                    "artreq",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="art_req.ArtReq"),
                ),
            ],
        ),
    ]
