# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("art_req", "0002_product_case_pack"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflow", "0001_initial"),
        ("qad_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="workflow.ItemCatalog"),
        ),
        migrations.AddField(
            model_name="partialartreq",
            name="artReq",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="art_req.ArtReq",
            ),
        ),
        migrations.AddField(
            model_name="partialartreq",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="extraproof",
            name="artreq",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="art_req.ArtReq"),
        ),
        migrations.AddField(
            model_name="artreq",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artreq_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="artreq",
            name="csr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artreq_csr",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="artreq",
            name="mkt_segment",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="art_req.MarketSegment"),
        ),
        migrations.AddField(
            model_name="artreq",
            name="printgroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="qad_data.QAD_PrintGroups",
            ),
        ),
        migrations.AddField(
            model_name="artreq",
            name="sales_rep",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artreq_salesrep",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="artreq",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="art_req.ArtReq"),
        ),
    ]
