# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_req", "0003_auto_20180302_1702"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ink_jet_promo",
            field=models.BooleanField(default=False, verbose_name=b"Ink Jet Promo"),
        ),
        migrations.AddField(
            model_name="product",
            name="label_promo",
            field=models.BooleanField(default=False, verbose_name=b"Label Promo"),
        ),
    ]
