# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-26 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_req", "0004_auto_20190522_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="partialartreq",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
