# Generated by Django 2.2 on 2019-09-23 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_req", "0004_auto_20190522_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalinfo",
            name="forecast",
            field=models.CharField(
                choices=[
                    ("floorstock", "Floor Stock"),
                    ("makeandship", "Make and Ship"),
                    ("promotional", "Promotional"),
                ],
                max_length=255,
                verbose_name="Forecast",
            ),
        ),
        migrations.AlterField(
            model_name="additionalinfo",
            name="incoming_art_format",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Digital Art via E-mail"),
                    (2, "Original Art"),
                    (3, "Art to be created by Clemson"),
                    (4, "Recreate from Print Sample"),
                    (5, "ISDN or FTP"),
                    (6, "Digital art on Disk"),
                    (9, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="additionalinfo",
            name="prev_9_digit",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Previous 9-Digit #"
            ),
        ),
        migrations.AlterField(
            model_name="artreq",
            name="channel",
            field=models.CharField(
                choices=[("enduser", "End User"), ("distributor", "Distributor")],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="artreq",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="test"),
        ),
        migrations.AlterField(
            model_name="artreq",
            name="print_type",
            field=models.CharField(
                choices=[
                    ("stock", "Stock"),
                    ("local", "Local"),
                    ("national", "National"),
                    ("trade", "Trade"),
                    ("branded", "Branded"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="extraproof",
            name="ship_to_addy_1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Address 1"
            ),
        ),
        migrations.AlterField(
            model_name="extraproof",
            name="ship_to_addy_2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Address 2"
            ),
        ),
        migrations.AlterField(
            model_name="extraproof",
            name="ship_to_city",
            field=models.CharField(blank=True, max_length=255, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="extraproof",
            name="ship_to_company",
            field=models.CharField(blank=True, max_length=255, verbose_name="Company"),
        ),
        migrations.AlterField(
            model_name="extraproof",
            name="ship_to_country",
            field=models.CharField(blank=True, max_length=255, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="extraproof",
            name="ship_to_email",
            field=models.CharField(blank=True, max_length=255, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="extraproof",
            name="ship_to_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="extraproof",
            name="ship_to_phone",
            field=models.CharField(blank=True, max_length=255, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="extraproof",
            name="ship_to_state",
            field=models.CharField(blank=True, max_length=255, verbose_name="State"),
        ),
        migrations.AlterField(
            model_name="extraproof",
            name="ship_to_zip",
            field=models.CharField(blank=True, max_length=255, verbose_name="Zip"),
        ),
        migrations.AlterField(
            model_name="partialartreq",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation"),
        ),
        migrations.AlterField(
            model_name="partialartreq",
            name="last_updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last_updated"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="annual_usage",
            field=models.IntegerField(verbose_name="Annual Usage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="case_color",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Case Color"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="case_pack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qad_data.QAD_CasePacks",
                verbose_name="Case Pack",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="corr_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ipfb", "IPFB"),
                    ("gpi", "GPI"),
                    ("custom", "Custom"),
                    ("preprint", "Preprint"),
                ],
                default="gpi",
                max_length=255,
                verbose_name="Corrugated Type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="customer_number",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Customer Number"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ink_jet_promo",
            field=models.BooleanField(default=False, verbose_name="Ink Jet Promo"),
        ),
        migrations.AlterField(
            model_name="product",
            name="label_color",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Label Color"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="label_copy_1",
            field=models.CharField(
                blank=True, max_length=22, verbose_name="Label Copy 1"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="label_copy_2",
            field=models.CharField(
                blank=True, max_length=22, verbose_name="Label Copy 2"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="label_copy_3",
            field=models.CharField(
                blank=True, max_length=22, verbose_name="Label Copy 3"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="label_promo",
            field=models.BooleanField(default=False, verbose_name="Label Promo"),
        ),
        migrations.AlterField(
            model_name="product",
            name="mock_up",
            field=models.BooleanField(default=False, verbose_name="Mock-Ups"),
        ),
        migrations.AlterField(
            model_name="product",
            name="order_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Estimated Order Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="print_color",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Print Color"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ship_to_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AS", "American Samoa"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("AA", "Armed Forces Americas"),
                    ("AE", "Armed Forces Europe"),
                    ("AP", "Armed Forces Pacific"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DE", "Delaware"),
                    ("DC", "District of Columbia"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("GU", "Guam"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("KY", "Kentucky"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("MP", "Northern Mariana Islands"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("PR", "Puerto Rico"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VI", "Virgin Islands"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WV", "West Virginia"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                ],
                max_length=2,
                verbose_name="Ship to State",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sleeve_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Sleeve Count"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="wrap_proof",
            field=models.BooleanField(default=False, verbose_name="Wrap Proof"),
        ),
    ]
