# Generated by Django 2.2 on 2019-10-02 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("art_req", "0005_partialartreq_is_completed"),
        ("art_req", "0005_auto_20190923_1111"),
    ]

    operations = []
