# Generated by Django 2.2.28 on 2023-06-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_req", "0006_merge_20191002_1022"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="render",
            field=models.BooleanField(default=False, verbose_name="Render"),
        ),
    ]
