# Generated by Django 5.2.6 on 2025-09-13 08:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_req", "0036_stabilize_ship_to_state"),
        ("qad_data", "0004_alter_qad_casepacks_id_alter_qad_printgroups_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artreq",
            options={"ordering": ["-creation_date"], "verbose_name": "Art Request", "verbose_name_plural": "Art Requests"},
        ),
        migrations.AlterModelOptions(
            name="partialartreq",
            options={
                "ordering": ["-last_updated"],
                "verbose_name": "Partial Art Request",
                "verbose_name_plural": "Partial Art Requests",
            },
        ),
        migrations.AlterField(
            model_name="artreq",
            name="channel",
            field=models.CharField(
                choices=[("enduser", "End User"), ("distributor", "Distributor")],
                help_text="Distribution channel for this request",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="artreq",
            name="contact_email",
            field=models.EmailField(help_text="Primary contact email for this request", max_length=255),
        ),
        migrations.AlterField(
            model_name="artreq",
            name="contact_name",
            field=models.CharField(help_text="Primary contact for this request", max_length=255),
        ),
        migrations.AlterField(
            model_name="artreq",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="artreq",
            name="design_name",
            field=models.CharField(help_text="Primary design identifier", max_length=255),
        ),
        migrations.AlterField(
            model_name="artreq",
            name="mkt_segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="art_req.marketsegment", verbose_name="Market Segment"
            ),
        ),
        migrations.AlterField(
            model_name="artreq",
            name="print_type",
            field=models.CharField(
                choices=[("stock", "Stock"), ("local", "Local"), ("national", "National"), ("trade", "Trade"), ("branded", "Branded")],
                max_length=25,
                verbose_name="Print Type",
            ),
        ),
        migrations.AlterField(
            model_name="artreq",
            name="printgroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="qad_data.qad_printgroups", verbose_name="Print Group"
            ),
        ),
        migrations.AlterField(
            model_name="partialartreq",
            name="artReq",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="art_req.artreq", verbose_name="Art Request"
            ),
        ),
        migrations.AlterField(
            model_name="partialartreq",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partial_artreq_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="partialartreq",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="partialartreq",
            name="fieldData",
            field=models.TextField(blank=True, null=True, verbose_name="Field Data"),
        ),
        migrations.AlterField(
            model_name="partialartreq",
            name="fileData",
            field=models.TextField(blank=True, null=True, verbose_name="File Data"),
        ),
        migrations.AlterField(
            model_name="partialartreq",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Completed"),
        ),
        migrations.AlterField(
            model_name="partialartreq",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name="Last Updated"),
        ),
        migrations.AlterField(
            model_name="partialartreq",
            name="partial_name",
            field=models.CharField(max_length=255, verbose_name="Partial Name"),
        ),
        migrations.AddIndex(
            model_name="artreq",
            index=models.Index(fields=["job_num"], name="art_req_art_job_num_a74624_idx"),
        ),
        migrations.AddIndex(
            model_name="artreq",
            index=models.Index(fields=["creation_date"], name="art_req_art_creatio_88e409_idx"),
        ),
        migrations.AddIndex(
            model_name="artreq",
            index=models.Index(fields=["sales_rep", "creation_date"], name="art_req_art_sales_r_27070d_idx"),
        ),
    ]
