# Generated by Django 5.2.6 on 2025-09-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_req", "0037_alter_artreq_options_alter_partialartreq_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partialartreq",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
    ]
