"use strict";
// This file is auto-generated by @hey-api/openapi-ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersService = exports.RestService = void 0;
const OpenAPI_1 = require("./core/OpenAPI");
const request_1 = require("./core/request");
class RestService {
    /**
     * Check REST API
     * This endpoint checks if the REST API is working.
     * @returns Message
     * @throws ApiError
     */
    static restRestCheckRetrieve() {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "GET",
            url: "/api/rest/rest-check/",
        });
    }
}
exports.RestService = RestService;
class UsersService {
    /**
     * @param data The data for the request.
     * @param data.limit Number of results to return per page.
     * @param data.offset The initial index from which to return the results.
     * @returns PaginatedUserList
     * @throws ApiError
     */
    static usersList(data = {}) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "GET",
            url: "/api/users/",
            query: {
                limit: data.limit,
                offset: data.offset,
            },
        });
    }
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns User
     * @throws ApiError
     */
    static usersCreate(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "POST",
            url: "/api/users/",
            body: data.requestBody,
            mediaType: "application/json",
        });
    }
    /**
     * @param data The data for the request.
     * @param data.id A unique integer value identifying this user.
     * @returns User
     * @throws ApiError
     */
    static usersRetrieve(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "GET",
            url: "/api/users/{id}/",
            path: {
                id: data.id,
            },
        });
    }
    /**
     * @param data The data for the request.
     * @param data.id A unique integer value identifying this user.
     * @param data.requestBody
     * @returns User
     * @throws ApiError
     */
    static usersUpdate(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "PUT",
            url: "/api/users/{id}/",
            path: {
                id: data.id,
            },
            body: data.requestBody,
            mediaType: "application/json",
        });
    }
    /**
     * @param data The data for the request.
     * @param data.id A unique integer value identifying this user.
     * @param data.requestBody
     * @returns User
     * @throws ApiError
     */
    static usersPartialUpdate(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "PATCH",
            url: "/api/users/{id}/",
            path: {
                id: data.id,
            },
            body: data.requestBody,
            mediaType: "application/json",
        });
    }
    /**
     * @param data The data for the request.
     * @param data.id A unique integer value identifying this user.
     * @returns void No response body
     * @throws ApiError
     */
    static usersDestroy(data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "DELETE",
            url: "/api/users/{id}/",
            path: {
                id: data.id,
            },
        });
    }
}
exports.UsersService = UsersService;
