"use strict";
// This file is auto-generated by @hey-api/openapi-ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersService = exports.RestService = void 0;
var OpenAPI_1 = require("./core/OpenAPI");
var request_1 = require("./core/request");
var RestService = /** @class */ (function () {
    function RestService() {
    }
    /**
     * Check REST API
     * This endpoint checks if the REST API is working.
     * @returns Message
     * @throws ApiError
     */
    RestService.restRestCheckRetrieve = function () {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "GET",
            url: "/api/rest/rest-check/",
        });
    };
    return RestService;
}());
exports.RestService = RestService;
var UsersService = /** @class */ (function () {
    function UsersService() {
    }
    /**
     * @param data The data for the request.
     * @param data.limit Number of results to return per page.
     * @param data.offset The initial index from which to return the results.
     * @returns PaginatedUserList
     * @throws ApiError
     */
    UsersService.usersList = function (data) {
        if (data === void 0) { data = {}; }
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "GET",
            url: "/api/users/",
            query: {
                limit: data.limit,
                offset: data.offset,
            },
        });
    };
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns User
     * @throws ApiError
     */
    UsersService.usersCreate = function (data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "POST",
            url: "/api/users/",
            body: data.requestBody,
            mediaType: "application/json",
        });
    };
    /**
     * @param data The data for the request.
     * @param data.id A unique integer value identifying this user.
     * @returns User
     * @throws ApiError
     */
    UsersService.usersRetrieve = function (data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "GET",
            url: "/api/users/{id}/",
            path: {
                id: data.id,
            },
        });
    };
    /**
     * @param data The data for the request.
     * @param data.id A unique integer value identifying this user.
     * @param data.requestBody
     * @returns User
     * @throws ApiError
     */
    UsersService.usersUpdate = function (data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "PUT",
            url: "/api/users/{id}/",
            path: {
                id: data.id,
            },
            body: data.requestBody,
            mediaType: "application/json",
        });
    };
    /**
     * @param data The data for the request.
     * @param data.id A unique integer value identifying this user.
     * @param data.requestBody
     * @returns User
     * @throws ApiError
     */
    UsersService.usersPartialUpdate = function (data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "PATCH",
            url: "/api/users/{id}/",
            path: {
                id: data.id,
            },
            body: data.requestBody,
            mediaType: "application/json",
        });
    };
    /**
     * @param data The data for the request.
     * @param data.id A unique integer value identifying this user.
     * @returns void No response body
     * @throws ApiError
     */
    UsersService.usersDestroy = function (data) {
        return (0, request_1.request)(OpenAPI_1.OpenAPI, {
            method: "DELETE",
            url: "/api/users/{id}/",
            path: {
                id: data.id,
            },
        });
    };
    return UsersService;
}());
exports.UsersService = UsersService;
