# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcatalog",
            name="product_substrate",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, b"Single Poly"),
                    (2, b"Double Poly"),
                    (3, b"Clay Coated"),
                    (4, b"Clear Plastic"),
                    (5, b"White Plastic"),
                    (6, b"Kraft Board"),
                    (7, b"Clay Coated Bag"),
                    (9, b"PLA"),
                    (10, b"CRB"),
                    (8, b"Post Consumer Fiber"),
                    (11, b"N/A"),
                ],
                null=True,
                verbose_name=b"Substrate",
            ),
        ),
    ]
