# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0003_auto_20180601_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcatalog",
            name="product_board",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, b"Double Poly"),
                    (2, b"Single Poly"),
                    (3, b"Single PLA"),
                    (4, b"Double PLA"),
                    (5, b"Front Side SBS (Clay)"),
                    (6, b"Back Side SBS"),
                    (7, b"Kraft"),
                    (8, b"CRB"),
                    (9, b"Single PCF"),
                    (10, b"Double PCF"),
                    (11, b"Clear Plastic"),
                ],
                null=True,
                verbose_name=b"Board",
            ),
        ),
    ]
