# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0004_itemcatalog_product_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcatalog",
            name="product_board",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, b"Double Poly"),
                    (2, b"Single Poly"),
                    (3, b"Single PLA"),
                    (4, b"Double PLA"),
                    (5, b"Clay Coated"),
                    (6, b"Bare SBS"),
                    (7, b"Kraft"),
                    (8, b"CRB"),
                    (9, b"Single PCF"),
                    (10, b"Double PCF"),
                    (11, b"Clear Plastic"),
                ],
                null=True,
                verbose_name=b"Board",
            ),
        ),
    ]
