# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0005_auto_20181024_1548"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcatalog",
            name="item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (b"HC", b"Hot Cup"),
                    (b"CC", b"Cold Cup"),
                    (b"WP", b"White Plastic"),
                    (b"CP", b"Clear Plastic"),
                    (b"TP", b"Translucent Plastic"),
                    (b"KB", b"Kraft"),
                    (b"BG", b"Bag"),
                    (b"MS", b"Misc"),
                    (b"CT", b"Carton"),
                    (b"PN", b"Panel"),
                    (b"KC", b"Kraft Corrugated"),
                    (b"WC", b"White Corrugated"),
                    (b"LD", b"Lid"),
                    (b"FT", b"Food Tray"),
                    (b"OT", b"Other"),
                ],
                max_length=20,
            ),
        ),
    ]
