# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0007_auto_20190208_1410"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcatalog",
            name="comments",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
