# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0008_itemcatalog_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    (b"BillableSales", b"Billable - Sales"),
                    (b"BillablePlants", b"Billable - Plants"),
                    (b"BillableMarketing", b"Billable - Marketing"),
                    (b"CostAvoidance", b"Cost Avoidance"),
                    (b"Transition", b"Transition"),
                    (b"CreativeSales", b"Creative - Sales"),
                    (b"CreativeMarketing", b"Creative - Marketing"),
                ],
                max_length=100,
            ),
        ),
    ]
