# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 09:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0009_job_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobComplexity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            (b"RebuildNoArt", b"Rebuild - No Art"),
                            (b"RebuildSomeArt", b"Rebuild - Some Art"),
                            (b"NewGPIStraightTemp", b"New - GPI Straight Temp"),
                            (b"NewGPICurvedTemp", b"New - GPI Curved Temp"),
                            (
                                b"NewCompetStraightTemp",
                                b"New - Competitor Straight Temp",
                            ),
                            (b"NewCompetCurvedTemp", b"New - Competitor Curved Temp"),
                            (b"RevGPIArt", b"Revision - GPI Artwork"),
                            (b"Creative", b"Creative"),
                            (b"SpecSheet", b"Spec Sheet"),
                            (b"Other", b"Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "complexity",
                    models.CharField(
                        blank=True,
                        choices=[(b"A", b"A"), (b"B", b"B"), (b"C", b"C")],
                        max_length=100,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workflow.Job"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Job Complexity",
            },
        ),
    ]
