# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0010_jobcomplexity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcomplexity",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    (b"RebuildNoArt", b"Rebuild - No Art"),
                    (b"RebuildSomeArt", b"Rebuild - Some Art"),
                    (b"NewGPIStraightTemp", b"New - GPI Straight Temp"),
                    (b"NewGPICurvedTemp", b"New - GPI Curved Temp"),
                    (b"NewCompetStraightTemp", b"New - Competitor Straight Temp"),
                    (b"NewCompetCurvedTemp", b"New - Competitor Curved Temp"),
                    (b"RevGPIArt", b"Revision - GPI Artwork"),
                    (b"Creative", b"Creative"),
                    (b"SpecSheet", b"Spec Sheet"),
                    (b"Other", b"Other"),
                    (b"CorrugatedCustom", b"Corrugated - Custom"),
                    (b"CorrugatedAuto", b"Corrugated - Auto"),
                ],
                max_length=100,
            ),
        ),
    ]
