# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0011_auto_20190625_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platepackage",
            name="platetype",
            field=models.CharField(
                choices=[
                    (b"Conv", b"Conventional Flexo"),
                    (b"Digi", b"Digital Flexo"),
                    (b"DigiLux", b"Digital Lux"),
                    (b"DigiLuxHD", b"Digital Lux HD"),
                    (b"DigiLuxMcD", b"Digital Lux McD"),
                    (b"Rub", b"Rubber Flexo"),
                    (b"Lth", b"Litho"),
                    (b"Grv", b"Gravure"),
                    (b"Off", b"Offset Flexo"),
                    (b"Oth", b"Other"),
                    (b"NA", b"N/A"),
                    (b"Corrugate", b"Corrugated"),
                ],
                max_length=50,
            ),
        ),
    ]
