# Generated by Django 2.2 on 2020-02-08 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0012_auto_20191107_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Billed"),
        ),
        migrations.AlterField(
            model_name="charge",
            name="invoice_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date Invoiced"),
        ),
        migrations.AlterField(
            model_name="chargetype",
            name="rush_type",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("FSBMULTH", "Foodservice High Multiplier"),
                    ("FSBMULTL", "Foodservice Low Multiplier"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="assignment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date Printlocation Assigned"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Entered"),
        ),
        migrations.AlterField(
            model_name="item",
            name="demand_plan_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Demand Planning Date"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="electronic_proof_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="electronic proof date"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="file_delivery_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="file delivery date"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="fsb_nine_digit_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="fsb nine digit creation date"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="inkbook",
            field=models.IntegerField(
                choices=[(1, "GCH"), (2, "PMS"), (3, "OTHER")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_situation",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Lost to Competitor"),
                    (2, "New Job Entered"),
                    (3, "Size Not Needed"),
                    (4, "Not Enough Volume"),
                    (5, "Speculative Art"),
                    (11, "Combo Pack Item"),
                    (6, "Wraps Only"),
                    (9, "Stalled"),
                    (7, "No Response"),
                    (10, "Canceled: Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_status",
            field=models.CharField(default="Pending", max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="last_modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date Last Modified"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="mkt_review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Marketing Review Date"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="plant_review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Plant Review Date"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="preflight_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="preflight date"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="proof_reminder_email_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Proof Reminder Sent"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="quality",
            field=models.CharField(
                blank=True, choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="itemcatalog",
            name="item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HC", "Hot Cup"),
                    ("CC", "Cold Cup"),
                    ("WP", "White Plastic"),
                    ("CP", "Clear Plastic"),
                    ("TP", "Translucent Plastic"),
                    ("KB", "Kraft"),
                    ("BG", "Bag"),
                    ("MS", "Misc"),
                    ("CT", "Carton"),
                    ("PN", "Panel"),
                    ("KC", "Kraft Corrugated"),
                    ("WC", "White Corrugated"),
                    ("LD", "Lid"),
                    ("FT", "Food Tray"),
                    ("OT", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="itemcatalog",
            name="last_edit",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Edit Date"),
        ),
        migrations.AlterField(
            model_name="itemcatalog",
            name="mfg_name",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="MFG Name",
            ),
        ),
        migrations.AlterField(
            model_name="itemcatalog",
            name="product_board",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Double Poly"),
                    (2, "Single Poly"),
                    (3, "Single PLA"),
                    (4, "Double PLA"),
                    (5, "Clay Coated"),
                    (6, "Bare SBS"),
                    (7, "Kraft"),
                    (8, "CRB"),
                    (9, "Single PCF"),
                    (10, "Double PCF"),
                    (11, "Clear Plastic"),
                ],
                null=True,
                verbose_name="Board",
            ),
        ),
        migrations.AlterField(
            model_name="itemcatalog",
            name="product_substrate",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Single Poly"),
                    (2, "Double Poly"),
                    (3, "Clay Coated"),
                    (4, "Clear Plastic"),
                    (5, "White Plastic"),
                    (12, "Translucent Plastic"),
                    (6, "Kraft Board"),
                    (7, "Clay Coated Bag"),
                    (9, "PLA"),
                    (10, "CRB"),
                    (11, "Post Consumer Fiber"),
                    (8, "N/A"),
                ],
                null=True,
                verbose_name="Substrate",
            ),
        ),
        migrations.AlterField(
            model_name="itemcatalog",
            name="productsubcategory",
            field=models.ManyToManyField(
                blank=True,
                related_name="itemcatalog_set",
                to="item_catalog.ProductSubCategory",
                verbose_name="Prod. Category",
            ),
        ),
        migrations.AlterField(
            model_name="itemcatalogphoto",
            name="last_edit",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Edit Date"),
        ),
        migrations.AlterField(
            model_name="itemcolor",
            name="delta_e_passes",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="itemreview",
            name="review_catagory",
            field=models.CharField(
                choices=[
                    ("plant", "Plant Review"),
                    ("demand", "Demand Review"),
                    ("market", "Marketing Review"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="itemreview",
            name="review_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date Reviewed"),
        ),
        migrations.AlterField(
            model_name="itemreview",
            name="review_initiated_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date Review Initiated"
            ),
        ),
        migrations.AlterField(
            model_name="itemspec",
            name="case_dim_d",
            field=models.CharField(
                blank=True, max_length=25, verbose_name="Case depth"
            ),
        ),
        migrations.AlterField(
            model_name="itemspec",
            name="case_dim_h",
            field=models.CharField(
                blank=True, max_length=25, verbose_name="Case height"
            ),
        ),
        migrations.AlterField(
            model_name="itemspec",
            name="case_dim_w",
            field=models.CharField(
                blank=True, max_length=25, verbose_name="Case width"
            ),
        ),
        migrations.AlterField(
            model_name="itemspec",
            name="case_wt",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Case weight"
            ),
        ),
        migrations.AlterField(
            model_name="itemspec",
            name="horizontal",
            field=models.FloatField(blank=True, null=True, verbose_name="Art width"),
        ),
        migrations.AlterField(
            model_name="itemspec",
            name="total_print_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Total Print Area",
            ),
        ),
        migrations.AlterField(
            model_name="itemspec",
            name="vertical",
            field=models.FloatField(blank=True, null=True, verbose_name="Art height"),
        ),
        migrations.AlterField(
            model_name="itemtracker",
            name="addition_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date Added"),
        ),
        migrations.AlterField(
            model_name="itemtracker",
            name="removal_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date Removed"),
        ),
        migrations.AlterField(
            model_name="job",
            name="art_rec_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Digital Art via E-mail"),
                    (2, "Original Art"),
                    (3, "Art to be created by Clemson"),
                    (4, "Recreate from Print Sample"),
                    (5, "ISDN or FTP"),
                    (6, "Digital art on Disk"),
                    (9, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="bill_to_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BTC", "Bill To Customer"),
                    ("AMO", "Absorbed MFG Operations"),
                    ("APR", "Absorbed To Project (2007 RAT)"),
                    ("ASN", "Absorbed Sales New"),
                    ("ASP", "Absorbed Sales Policy"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="business_type",
            field=models.CharField(
                blank=True, choices=[("NEW", "New"), ("EXT", "Existing")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Entered"),
        ),
        migrations.AlterField(
            model_name="job",
            name="customer_po_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Customer PO#"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Due Date"),
        ),
        migrations.AlterField(
            model_name="job",
            name="last_modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date Last Modified"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="olmsted_po_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="PO# (Olmsted)"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="prepress_supplier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OPT", "Optihue"),
                    ("PHT", "Phototype"),
                    ("SHK", "Schawk"),
                    ("SGS", "Southern Graphics"),
                ],
                max_length=50,
                verbose_name="Prepress Sup.",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="real_due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Real Due Date"),
        ),
        migrations.AlterField(
            model_name="job",
            name="sales_service_rep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.SalesServiceRep",
                verbose_name="Sales Rep.",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Active", "Active"),
                    ("Hold", "Hold"),
                    ("Complete", "Complete"),
                    ("CompleteBilled", "Complete & Billed"),
                    ("Cancelled", "Cancelled"),
                    ("ClosedATP", "Closed - Absorbed to Plant"),
                    ("ClosedATS", "Closed - Absorbed to Sales"),
                    ("ClosedBTC", "Closed - Bill to Customer"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="todo_list_mode",
            field=models.IntegerField(
                choices=[(0, "Default"), (1, "Stickied"), (2, "Hidden")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BillableSales", "Billable - Sales"),
                    ("BillablePlants", "Billable - Plants"),
                    ("BillableMarketing", "Billable - Marketing"),
                    ("CostAvoidance", "Cost Avoidance"),
                    ("Transition", "Transition"),
                    ("CreativeSales", "Creative - Sales"),
                    ("CreativeMarketing", "Creative - Marketing"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="use_new_bev_nomenclature",
            field=models.BooleanField(default=True, verbose_name="New Nomenclature"),
        ),
        migrations.AlterField(
            model_name="jobcomplexity",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RebuildNoArt", "Rebuild - No Art"),
                    ("RebuildSomeArt", "Rebuild - Some Art"),
                    ("NewGPIStraightTemp", "New - GPI Straight Temp"),
                    ("NewGPICurvedTemp", "New - GPI Curved Temp"),
                    ("NewCompetStraightTemp", "New - Competitor Straight Temp"),
                    ("NewCompetCurvedTemp", "New - Competitor Curved Temp"),
                    ("RevGPIArt", "Revision - GPI Artwork"),
                    ("Creative", "Creative"),
                    ("SpecSheet", "Spec Sheet"),
                    ("Other", "Other"),
                    ("CorrugatedCustom", "Corrugated - Custom"),
                    ("CorrugatedAuto", "Corrugated - Auto"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="jobcomplexity",
            name="complexity",
            field=models.CharField(
                blank=True, choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="plateorder",
            name="date_entered",
            field=models.DateField(auto_now_add=True, verbose_name="Date Entered"),
        ),
        migrations.AlterField(
            model_name="plateorder",
            name="date_needed",
            field=models.DateField(blank=True, null=True, verbose_name="Date Needed"),
        ),
        migrations.AlterField(
            model_name="plateorder",
            name="invoice_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Order Invoice Date"
            ),
        ),
        migrations.AlterField(
            model_name="plateorder",
            name="stage1_complete_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Stage1 Complete Date"
            ),
        ),
        migrations.AlterField(
            model_name="plateorder",
            name="stage2_complete_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Stage2 Complete Date"
            ),
        ),
        migrations.AlterField(
            model_name="platepackage",
            name="platetype",
            field=models.CharField(
                choices=[
                    ("Conv", "Conventional Flexo"),
                    ("Digi", "Digital Flexo"),
                    ("DigiLux", "Digital Lux"),
                    ("DigiLuxHD", "Digital Lux HD"),
                    ("DigiLuxMcD", "Digital Lux McD"),
                    ("Rub", "Rubber Flexo"),
                    ("Lth", "Litho"),
                    ("Grv", "Gravure"),
                    ("Off", "Offset Flexo"),
                    ("Oth", "Other"),
                    ("NA", "N/A"),
                    ("Corrugate", "Corrugated"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="complete_date",
            field=models.DateField(blank=True, null=True, verbose_name="Complete Date"),
        ),
        migrations.AlterField(
            model_name="revision",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Entered"),
        ),
        migrations.AlterField(
            model_name="revision",
            name="due_date",
            field=models.DateField(verbose_name="Due Date"),
        ),
        migrations.AlterField(
            model_name="stepspec",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date created"),
        ),
        migrations.AlterField(
            model_name="stepspec",
            name="eng_num",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Engineering drawing number"
            ),
        ),
        migrations.AlterField(
            model_name="stepspec",
            name="last_edit",
            field=models.DateTimeField(auto_now=True, verbose_name="Last edit date"),
        ),
        migrations.AlterField(
            model_name="stepspec",
            name="num_blanks",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of blanks"
            ),
        ),
        migrations.AlterField(
            model_name="stepspec",
            name="num_colors",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of colors"
            ),
        ),
        migrations.AlterField(
            model_name="stepspec",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "Created"),
                    ("checked", "Checked"),
                    ("verified", "Verified"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stepspec",
            name="template_horizontal",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Template width"
            ),
        ),
        migrations.AlterField(
            model_name="stepspec",
            name="template_vertical",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Template height"
            ),
        ),
        migrations.AlterField(
            model_name="trackedart",
            name="addition_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date Added"),
        ),
        migrations.AlterField(
            model_name="trackedart",
            name="art_catagory",
            field=models.CharField(
                choices=[
                    ("ecotainer", "Ecotainer Logo"),
                    ("hold_go", "Hold & Go Logo"),
                    ("bpi", "BPI Logo"),
                    ("din_certo", "Din Certo Logo"),
                    ("sfi", "SFI Label"),
                    ("fsc", "FSC Label"),
                    ("pefc", "PEFC Label"),
                    ("misc_enviro", "Misc. Enviromental Messaging"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="trackedart",
            name="removal_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date Removed"),
        ),
    ]
