# Generated by Django 2.2 on 2020-04-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0013_auto_20200208_1021"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProofTracker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(verbose_name="Date Printed")),
                ("copies", models.IntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workflow.Item"
                    ),
                ),
            ],
        ),
    ]
