# Generated by Django 2.2 on 2020-04-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0014_prooftracker"),
    ]

    operations = [
        migrations.AddField(
            model_name="prooftracker",
            name="xml_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
