# Generated by Django 2.2 on 2020-04-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0015_prooftracker_xml_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="prooftracker",
            name="proofer",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
