# Generated by Django 2.2 on 2020-05-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0016_prooftracker_proofer"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="coating_pattern",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="item",
            name="distortion",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="graphic_req_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="item",
            name="is_carton",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.CharField(blank=True, default="Outside", max_length=255),
        ),
        migrations.AddField(
            model_name="item",
            name="one_up_die",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="item",
            name="plate_thickness",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="item",
            name="print_repeat",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="process",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="item",
            name="product_group",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="item",
            name="profile",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="item",
            name="step_die",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="item",
            name="upc",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="customer_identifier",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="graphic_supplier",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
