# Generated by Django 2.2 on 2020-06-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0017_auto_20200528_1726"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="grn",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="item",
            name="graphic_req_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
