# Generated by Django 2.2 on 2020-06-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0018_auto_20200618_1408"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platepackage",
            name="platetype",
            field=models.CharField(
                choices=[
                    ("Conv", "Conventional Flexo"),
                    ("Digi", "Digital Flexo"),
                    ("DigiLux", "Digital Lux"),
                    ("DigiLuxHD", "Digital Lux HD"),
                    ("DigiLuxMcD", "Digital Lux McD"),
                    ("Rub", "Rubber Flexo"),
                    ("Lth", "Litho"),
                    ("Grv", "Gravure"),
                    ("Off", "Offset Flexo"),
                    ("Oth", "Other"),
                    ("NA", "N/A"),
                    ("Corrugate", "Corrugated"),
                    ("InTheRound", "InTheRound"),
                ],
                max_length=50,
            ),
        ),
    ]
