# Generated by Django 2.2 on 2020-08-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0019_auto_20200629_1026"),
    ]

    operations = [
        migrations.AddField(
            model_name="colorwarning",
            name="dismissal_notes",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="colorwarning",
            name="dismissed",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
