# Generated by Django 2.2 on 2020-08-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0020_auto_20200818_1326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="coating_pattern",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="grn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="product_group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="step_die",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
