# Generated by Django 2.2 on 2020-10-21 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflow", "0021_auto_20200825_1008"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="customer_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="proof_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COLOR_AND_COPY", "Color and Copy"),
                    ("COPY_ONLY", "Copy Only"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="pcss",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pcss_of_job_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
