# Generated by Django 2.2 on 2020-10-23 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflow", "0022_auto_20201021_1348"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="graphic_specialist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graphic_specialist_of_job_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
