# Generated by Django 2.2 on 2021-01-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0023_job_graphic_specialist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platepackage",
            name="platetype",
            field=models.CharField(
                choices=[
                    ("Conv", "Conventional Flexo"),
                    ("Digi", "Digital Flexo"),
                    ("DigiLux", "Digital Lux"),
                    ("DigiLuxHD", "Digital Lux HD"),
                    ("DigiLuxMcD", "Digital Lux McD"),
                    ("Rub", "Rubber Flexo"),
                    ("Lth", "Litho"),
                    ("Grv", "Gravure"),
                    ("Off", "Offset Flexo"),
                    ("Oth", "Other"),
                    ("NA", "N/A"),
                    ("Corrugate", "Corrugated"),
                    ("InTheRound", "InTheRound"),
                    ("NX", "NX"),
                ],
                max_length=50,
            ),
        ),
    ]
