# Generated by Django 2.2 on 2021-01-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0024_auto_20210121_0915"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="graphic_po",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="sap_ship_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="sap_sold_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
