# Generated by Django 2.2 on 2021-03-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0026_item_kd_press"),
    ]

    operations = [
        migrations.AddField(
            model_name="colorwarning",
            name="notes",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
