# Generated by Django 2.2 on 2021-09-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0027_colorwarning_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="carton_type",
            field=models.CharField(
                blank=True,
                choices=[("Imposition", "Imposition"), ("Prepress", "Prepress")],
                max_length=100,
            ),
        ),
    ]
