# Generated by Django 2.2 on 2022-01-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0029_auto_20220119_1012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="plate_thickness",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="proof_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("COLOR_AND_COPY", "Color and Copy"),
                    ("COPY_ONLY", "Copy Only"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="carton_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Imposition", "Imposition"),
                    ("Prepress", "Prepress"),
                    ("PrepressandImposition", "Prepress and Imposition"),
                ],
                max_length=100,
            ),
        ),
    ]
