# Generated by Django 2.2 on 2022-01-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0030_auto_20220119_1342"),
    ]

    operations = [
        migrations.CreateModel(
            name="Substrate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Substrates",
            },
        ),
    ]
