# Generated by Django 2.2 on 2022-01-26 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0031_substrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="substrate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.Substrate",
            ),
        ),
    ]
