# Generated by Django 2.2 on 2022-02-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0032_item_substrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="gcr",
            field=models.BooleanField(default=False),
        ),
    ]
