# Generated by Django 2.2 on 2022-02-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0034_auto_20220215_0905"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="kd_press",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VERNON_5114", "Mt Vernon 5114 42”"),
                    ("VERNON_5190", "Mt Vernon 5190 50”"),
                    ("LINCOLN", "Lincoln"),
                    ("LINCOLN_50", "Lincoln 50”"),
                    ("LINCOLN_37_5", "Lincoln 37.5”"),
                    ("SANGER_38", "Sanger 38”"),
                    ("SANGER_40", "Sanger 40”"),
                    ("SANGER_50", "Sanger 50”"),
                    ("SANGER_66", "Sanger 66”"),
                    ("WESTROCK_3121", "WestRock 3121 38”"),
                    ("WESTROCK_3122", "WestRock 3122 35.4”"),
                    ("WESTROCK_3131", "WestRock 3131/32 50”"),
                    ("WESTROCK_4521", "WestRock 4521/22 66”"),
                ],
                max_length=50,
            ),
        ),
    ]
