# Generated by Django 2.2 on 2022-02-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0035_auto_20220215_1042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="proof_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("COLOR_AND_COPY", "Color and Copy"),
                    ("COPY_ONLY", "Copy Only"),
                    ("EDITS_ORIGINAL", "Edits to Original"),
                    ("EDIT_ORIGINAL_SWATCHES", "Edits to Original w Swatches"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
