# Generated by Django 2.2 on 2022-03-29 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0036_auto_20220217_1042"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartonWorkflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Carton Workflows",
            },
        ),
        migrations.CreateModel(
            name="InkSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Ink Sets",
            },
        ),
        migrations.CreateModel(
            name="LineScreen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Line Screens",
            },
        ),
        migrations.CreateModel(
            name="PrintCondition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Print Conditions",
            },
        ),
        migrations.CreateModel(
            name="Trap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Traps",
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="proof_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("COLOR_AND_COPY", "Color and Copy"),
                    ("COPY_ONLY", "Copy Only"),
                    ("EDITS_ORIGINAL", "Edits to Original"),
                    ("EDITS_ORIGINAL_SWATCHES", "Edits to Original w Swatches"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CartonProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "carton_workflow",
                    models.ManyToManyField(
                        related_name="carton_workflows", to="workflow.CartonWorkflow"
                    ),
                ),
                (
                    "ink_set",
                    models.ManyToManyField(
                        related_name="ink_sets", to="workflow.InkSet"
                    ),
                ),
                (
                    "line_screen",
                    models.ManyToManyField(
                        related_name="line_screens", to="workflow.LineScreen"
                    ),
                ),
                (
                    "print_condition",
                    models.ManyToManyField(
                        related_name="print_conditions", to="workflow.PrintCondition"
                    ),
                ),
                (
                    "print_location",
                    models.ManyToManyField(
                        related_name="print_locations", to="workflow.PrintLocation"
                    ),
                ),
                (
                    "substrate",
                    models.ManyToManyField(
                        related_name="substrates", to="workflow.Substrate"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Carton Profiles",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="carton_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.CartonProfile",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="carton_workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.CartonWorkflow",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="ink_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.InkSet",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="line_screen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.LineScreen",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="print_condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.PrintCondition",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="trap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.Trap",
            ),
        ),
    ]
