# Generated by Django 2.2 on 2022-05-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0038_auto_20220524_1050"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="proof_type_notes",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
