# Generated by Django 2.2 on 2022-08-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0041_auto_20220803_1325"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="ecg",
            field=models.BooleanField(default=False),
        ),
    ]
