# Generated by Django 2.2 on 2022-09-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0042_item_ecg"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="duplication_type",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
