# Generated by Django 2.2.28 on 2023-06-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0043_job_duplication_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="render",
            field=models.BooleanField(default=False),
        ),
    ]
