# Generated by Django 2.2 on 2025-02-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0044_item_render"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="purchase_request_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="EVG Purchase Request Number"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="olmsted_po_number",
            field=models.CharField(blank=True, max_length=100, verbose_name="PO#"),
        ),
    ]
