# Generated by Django 5.2.5 on 2025-08-30 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0044_item_render"),
        ("workflow", "0045_auto_20250223_2048"),
    ]

    operations = []
