# Generated by Django 5.2.6 on 2025-09-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0001_initial_squashed_0047_alter_beveragebrandcode_id_and_more"),
    ]

    operations = [
        # Add indexes for Job model
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_deleted", "status"],
                name="workflow_job_is_deleted_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["due_date"], name="workflow_job_due_date_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["creation_date"], name="workflow_job_creation_date_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["last_modified"], name="workflow_job_last_modified_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["artist"], name="workflow_job_artist_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["salesperson"], name="workflow_job_salesperson_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["workflow"], name="workflow_job_workflow_idx"),
        ),
        # Add indexes for Item model
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["is_deleted", "item_status"],
                name="workflow_item_is_deleted_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["job"], name="workflow_item_job_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["creation_date"], name="workflow_item_creation_date_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["last_modified"], name="workflow_item_last_modified_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["preflight_date"], name="workflow_item_preflight_date_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["electronic_proof_date"],
                name="workflow_item_electronic_proof_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["file_delivery_date"],
                name="workflow_item_file_delivery_date_idx",
            ),
        ),
    ]
