# Generated by Django 5.2.6 on 2025-09-13 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0048_auto_20250912_1635"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantBevController",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "db_table": "workflow_plant_bev_controller",
            },
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="workflow_it_is_dele_d02114_idx",
            old_name="workflow_item_is_deleted_status_idx",
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="workflow_it_job_id_e9617e_idx",
            old_name="workflow_item_job_idx",
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="workflow_it_creatio_4a44c8_idx",
            old_name="workflow_item_creation_date_idx",
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="workflow_it_last_mo_91d888_idx",
            old_name="workflow_item_last_modified_idx",
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="workflow_it_preflig_2f8dce_idx",
            old_name="workflow_item_preflight_date_idx",
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="workflow_it_electro_da4166_idx",
            old_name="workflow_item_electronic_proof_date_idx",
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="workflow_it_file_de_33db05_idx",
            old_name="workflow_item_file_delivery_date_idx",
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="workflow_jo_is_dele_dc19a3_idx",
            old_name="workflow_job_is_deleted_status_idx",
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="workflow_jo_due_dat_515a0f_idx",
            old_name="workflow_job_due_date_idx",
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="workflow_jo_creatio_e4441a_idx",
            old_name="workflow_job_creation_date_idx",
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="workflow_jo_last_mo_6b6fc1_idx",
            old_name="workflow_job_last_modified_idx",
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="workflow_jo_artist__0cae3f_idx",
            old_name="workflow_job_artist_idx",
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="workflow_jo_salespe_2fcf98_idx",
            old_name="workflow_job_salesperson_idx",
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="workflow_jo_workflo_47a583_idx",
            old_name="workflow_job_workflow_idx",
        ),
        migrations.AddField(
            model_name="plantbevcontroller",
            name="plant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="workflow.plant"),
        ),
        migrations.AddField(
            model_name="plantbevcontroller",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="plant",
            name="bev_controller",
            field=models.ManyToManyField(
                blank=True, related_name="beverage_controllers", through="workflow.PlantBevController", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plantbevcontroller",
            unique_together={("plant", "user")},
        ),
    ]
