services:
  postgres-dev:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: gchub_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro

volumes:
  postgres_dev_data:
