# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, b"General Information"),
                            (5, b"Warnings"),
                            (10, b"Error"),
                        ]
                    ),
                ),
                ("log_text", models.TextField()),
                (
                    "event_time",
                    models.DateTimeField(auto_now_add=True, verbose_name=b"Date"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Log",
                "verbose_name_plural": "Admin Logs",
            },
            managers=[
                ("create", django.db.models.manager.Manager()),
            ],
        ),
    ]
