# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_log", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminlog",
            name="event_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="adminlog",
            name="type",
            field=models.IntegerField(choices=[(0, "General Information"), (5, "Warnings"), (10, "Error")]),
        ),
    ]
