# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("queues", "0001_initial"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tifftopdf",
            name="item",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.Item",
            ),
        ),
        migrations.AddField(
            model_name="colorkeyqueue",
            name="item",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.Item",
            ),
        ),
    ]
