# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("queues", "0002_auto_20180302_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorkeyqueue",
            name="date_processed",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date Processed"),
        ),
        migrations.AlterField(
            model_name="colorkeyqueue",
            name="date_queued",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Queued"),
        ),
        migrations.AlterField(
            model_name="colorkeyqueue",
            name="number_of_attempts",
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Attempts"),
        ),
        migrations.AlterField(
            model_name="tifftopdf",
            name="date_processed",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date Processed"),
        ),
        migrations.AlterField(
            model_name="tifftopdf",
            name="date_queued",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Queued"),
        ),
    ]
