# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item_catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsubcategory",
            name="main_category",
            field=models.IntegerField(
                choices=[
                    (1, "Hot Cups"),
                    (2, "Cold Cups"),
                    (3, "Food Packaging"),
                    (4, "Evergreen Packaging"),
                ]
            ),
        ),
    ]
