# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import gchub_db.includes.model_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoxItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=64, unique=True)),
                (
                    "box_art",
                    models.FileField(blank=True, upload_to=b"autocorrugated_art"),
                ),
                ("english_description", models.CharField(blank=True, max_length=255)),
                ("spanish_description", models.CharField(blank=True, max_length=255)),
                ("french_description", models.CharField(blank=True, max_length=255)),
                (
                    "english_lid_description",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "spanish_lid_description",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "french_lid_description",
                    models.CharField(blank=True, max_length=255),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["item_name"],
            },
        ),
        migrations.CreateModel(
            name="BoxItemSpec",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.FloatField(blank=True, null=True)),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("case_count", models.IntegerField()),
                ("sleeve_count", models.IntegerField(blank=True, null=True)),
                ("is_first", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["boxitem__item_name"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedBox",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_type",
                    models.IntegerField(
                        choices=[
                            (0, b"Art with Label"),
                            (1, b"Art with Blank Label"),
                            (2, b"No Art with Label"),
                            (3, b"No Art with Blank Label"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name=b"Date Info Entered"),
                ),
                ("six_digit_num", models.IntegerField()),
                ("replaced_6digit", models.IntegerField(null=True)),
                ("nine_digit_num", models.IntegerField()),
                (
                    "fourteen_digit_num",
                    gchub_db.includes.model_fields.BigIntegerField(),
                ),
                ("text_line_1", models.CharField(max_length=120)),
                ("text_line_2", models.CharField(max_length=120)),
                ("sleeve_count", models.IntegerField()),
                ("dim_width", models.FloatField(verbose_name=b"Box Width")),
                ("dim_length", models.FloatField(verbose_name=b"Box Length")),
                ("dim_height", models.FloatField(verbose_name=b"Box Height")),
                ("board_spec", models.CharField(max_length=50)),
                ("case_color", models.CharField(max_length=75)),
                ("sfi_stamp_box", models.BooleanField(default=True)),
                (
                    "sfi_stamp_cup",
                    models.BooleanField(default=False, verbose_name=b"SFI Content Stamp"),
                ),
                ("blank_label", models.BooleanField(default=False)),
                (
                    "box_format",
                    models.IntegerField(choices=[(0, b"Left"), (1, b"Right")], default=0),
                ),
                (
                    "pdf_output",
                    models.FileField(blank=True, upload_to=b"autocorrugated_output"),
                ),
                ("approved", models.BooleanField(default=False)),
                ("make_slugs", models.BooleanField(default=False)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrugated_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_corrugated.BoxItem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Generated Boxes",
            },
        ),
        migrations.CreateModel(
            name="GeneratedLabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name=b"Date Info Entered"),
                ),
                ("nine_digit_num", models.IntegerField()),
                (
                    "fourteen_digit_num",
                    gchub_db.includes.model_fields.BigIntegerField(),
                ),
                ("text_line_1", models.CharField(max_length=120)),
                ("text_line_2", models.CharField(max_length=120)),
            ],
        ),
    ]
