# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auto_corrugated", "0001_initial"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedbox",
            name="job",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.Job",
            ),
        ),
        migrations.AddField(
            model_name="generatedbox",
            name="plant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="workflow.Plant"),
        ),
        migrations.AddField(
            model_name="generatedbox",
            name="platepackage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.PlatePackage",
            ),
        ),
        migrations.AddField(
            model_name="generatedbox",
            name="spec",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auto_corrugated.BoxItemSpec",
            ),
        ),
        migrations.AddField(
            model_name="boxitemspec",
            name="boxitem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auto_corrugated.BoxItem",
            ),
        ),
        migrations.AddField(
            model_name="boxitemspec",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.Plant",
            ),
        ),
        migrations.AddField(
            model_name="boxitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.ItemCatalog",
            ),
        ),
    ]
