# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_corrugated", "0002_auto_20180302_1702"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedbox",
            name="plate_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
