# Generated by Django 2.2 on 2019-09-23 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_corrugated", "0003_generatedbox_plate_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxitem",
            name="box_art",
            field=models.FileField(blank=True, upload_to="autocorrugated_art"),
        ),
        migrations.AlterField(
            model_name="boxitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"workflow__name": "Foodservice"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.ItemCatalog",
            ),
        ),
        migrations.AlterField(
            model_name="boxitemspec",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_in_acs": "True"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.Plant",
            ),
        ),
        migrations.AlterField(
            model_name="generatedbox",
            name="box_format",
            field=models.IntegerField(choices=[(0, "Left"), (1, "Right")], default=0),
        ),
        migrations.AlterField(
            model_name="generatedbox",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date Info Entered"
            ),
        ),
        migrations.AlterField(
            model_name="generatedbox",
            name="dim_height",
            field=models.FloatField(verbose_name="Box Height"),
        ),
        migrations.AlterField(
            model_name="generatedbox",
            name="dim_length",
            field=models.FloatField(verbose_name="Box Length"),
        ),
        migrations.AlterField(
            model_name="generatedbox",
            name="dim_width",
            field=models.FloatField(verbose_name="Box Width"),
        ),
        migrations.AlterField(
            model_name="generatedbox",
            name="job",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                limit_choices_to={"workflow__name": "Foodservice"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.Job",
            ),
        ),
        migrations.AlterField(
            model_name="generatedbox",
            name="pdf_output",
            field=models.FileField(blank=True, upload_to="autocorrugated_output"),
        ),
        migrations.AlterField(
            model_name="generatedbox",
            name="pdf_type",
            field=models.IntegerField(
                choices=[
                    (0, "Art with Label"),
                    (1, "Art with Blank Label"),
                    (2, "No Art with Label"),
                    (3, "No Art with Blank Label"),
                ],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generatedbox",
            name="plant",
            field=models.ForeignKey(
                limit_choices_to={"is_in_acs": "True"},
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.Plant",
            ),
        ),
        migrations.AlterField(
            model_name="generatedbox",
            name="platepackage",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"workflow__name": "Foodservice"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.PlatePackage",
            ),
        ),
        migrations.AlterField(
            model_name="generatedbox",
            name="sfi_stamp_cup",
            field=models.BooleanField(default=False, verbose_name="SFI Content Stamp"),
        ),
        migrations.AlterField(
            model_name="generatedlabel",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date Info Entered"
            ),
        ),
    ]
