# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-12 10:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflow", "0011_auto_20190625_1125"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSheet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours", models.FloatField()),
                ("comments", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeSheetCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="timesheet",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="timesheet.TimeSheetCategory",
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.Job",
            ),
        ),
    ]
