# Generated by Django 5.2.6 on 2025-09-11 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("accounts", "0001_initial"),
        ("accounts", "0002_userprofile_total_sick"),
        ("accounts", "0003_userprofile_machine_name"),
        ("accounts", "0004_auto_20190118_1333"),
        ("accounts", "0005_auto_20190425_1344"),
        ("accounts", "0006_auto_20190923_1111"),
        ("accounts", "0007_auto_20200217_1052"),
        ("accounts", "0008_userprofile_growl_hear_new_carton_jobs"),
        ("accounts", "0009_auto_20200921_1359"),
        ("accounts", "0010_auto_20201015_1352"),
        ("accounts", "0011_auto_20201023_0815"),
        ("accounts", "0012_auto_20210121_0915"),
        ("accounts", "0013_alter_userprofile_id"),
        ("accounts", "0014_userprofile_use_legacy_search"),
        ("accounts", "0015_userprofile_item_search_brand_and_more"),
        ("accounts", "0016_add_notifications_enabled"),
        ("accounts", "0017_add_theme_preferences"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.CharField(blank=True, max_length=50)),
                ("last_page_request", models.DateTimeField(blank=True, null=True)),
                (
                    "total_vacation",
                    models.IntegerField(default=0, editable=False, verbose_name="Total Vacation"),
                ),
                (
                    "growl_hear_approvals",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name="Item Approvals",
                    ),
                ),
                (
                    "growl_hear_jdf_processes",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name="JDF Events",
                    ),
                ),
                (
                    "growl_hear_new_beverage_jobs",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=0,
                        verbose_name="New Beverage Jobs",
                    ),
                ),
                (
                    "growl_hear_new_foodservice_jobs",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=0,
                        verbose_name="New Foodservice Jobs",
                    ),
                ),
                (
                    "growl_hear_9digit_entry",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name="9-Digit Number Entries",
                    ),
                ),
                (
                    "growl_hear_whoops",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name="Whoopsies!",
                    ),
                ),
                (
                    "growl_hear_revisions",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name="New Revisions",
                    ),
                ),
                (
                    "growl_hear_plant_rejections",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name="Plant Rejections",
                    ),
                ),
                (
                    "growl_hear_demand_planning_rejections",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name="Demand Planning Rejections",
                    ),
                ),
                (
                    "growl_hear_job_db_uploads",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name="Job Database Document Uploads",
                    ),
                ),
                (
                    "growl_hear_item_duplication",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name="Item Duplications/Press Changes",
                    ),
                ),
                (
                    "growl_hear_gold_changes",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=1,
                        verbose_name="GOLD Changes",
                    ),
                ),
                (
                    "growl_hear_todays_events",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name="Today's Events",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "total_sick",
                    models.IntegerField(default=5, editable=False, verbose_name="Total Sick"),
                ),
                ("machine_name", models.CharField(blank=True, max_length=100)),
                (
                    "growl_hear_new_carton_jobs",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Enabled"),
                            (2, "Enabled - Sticky"),
                        ],
                        default=0,
                        verbose_name="New Carton Jobs",
                    ),
                ),
                (
                    "use_legacy_search",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, job and item search will use the original GOLD interface",
                        verbose_name="Use Legacy Search Interface",
                    ),
                ),
                (
                    "item_search_brand",
                    models.BooleanField(
                        default=True,
                        help_text="Include brand field in item searches",
                        verbose_name="Search Brand Field",
                    ),
                ),
                (
                    "item_search_comments",
                    models.BooleanField(
                        default=True,
                        help_text="Include comments field in item searches",
                        verbose_name="Search Comments Field",
                    ),
                ),
                (
                    "item_search_customer",
                    models.BooleanField(
                        default=True,
                        help_text="Include customer field in item searches",
                        verbose_name="Search Customer Field",
                    ),
                ),
                (
                    "item_search_description",
                    models.BooleanField(
                        default=True,
                        help_text="Include item description field in item searches",
                        verbose_name="Search Item Description",
                    ),
                ),
                (
                    "item_search_specifications",
                    models.BooleanField(
                        default=True,
                        help_text="Include specifications field in item searches",
                        verbose_name="Search Specifications Field",
                    ),
                ),
                (
                    "item_search_upc",
                    models.BooleanField(
                        default=True,
                        help_text="Include UPC field in item searches",
                        verbose_name="Search UPC Field",
                    ),
                ),
                (
                    "job_search_artist",
                    models.BooleanField(
                        default=True,
                        help_text="Include artist field in job searches",
                        verbose_name="Search Artist Field",
                    ),
                ),
                (
                    "job_search_brand",
                    models.BooleanField(
                        default=True,
                        help_text="Include brand field in job searches",
                        verbose_name="Search Brand Field",
                    ),
                ),
                (
                    "job_search_comments",
                    models.BooleanField(
                        default=True,
                        help_text="Include comments field in job searches",
                        verbose_name="Search Comments Field",
                    ),
                ),
                (
                    "job_search_customer",
                    models.BooleanField(
                        default=True,
                        help_text="Include customer field in job searches",
                        verbose_name="Search Customer Field",
                    ),
                ),
                (
                    "job_search_instructions",
                    models.BooleanField(
                        default=True,
                        help_text="Include instructions field in job searches",
                        verbose_name="Search Instructions Field",
                    ),
                ),
                (
                    "job_search_po_number",
                    models.BooleanField(
                        default=True,
                        help_text="Include PO number field in job searches",
                        verbose_name="Search PO Number Field",
                    ),
                ),
                (
                    "job_search_salesperson",
                    models.BooleanField(
                        default=True,
                        help_text="Include salesperson field in job searches",
                        verbose_name="Search Salesperson Field",
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch to enable/disable all desktop notifications",
                        verbose_name="Enable All Notifications",
                    ),
                ),
                (
                    "custom_accent_color",
                    models.CharField(
                        blank=True,
                        help_text="Custom hex color code for accent theme color (e.g., #28a745)",
                        max_length=7,
                        null=True,
                        verbose_name="Custom Accent Color",
                    ),
                ),
                (
                    "custom_primary_color",
                    models.CharField(
                        blank=True,
                        help_text="Custom hex color code for primary theme color (e.g., #007bff)",
                        max_length=7,
                        null=True,
                        verbose_name="Custom Primary Color",
                    ),
                ),
                (
                    "enable_animations",
                    models.BooleanField(
                        default=True,
                        help_text="Enable smooth transitions and animations in the interface",
                        verbose_name="Enable Animations",
                    ),
                ),
                (
                    "preferred_theme",
                    models.CharField(
                        choices=[
                            ("default", "Default Theme"),
                            ("dark", "Dark Theme"),
                            ("light", "Light Theme"),
                        ],
                        default="default",
                        help_text="Choose your preferred color theme for the interface",
                        max_length=20,
                        verbose_name="Preferred Theme",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("in_artist_pulldown", "In Artist Pulldown"),
                    ("salesperson", "Salesperson/Analyst/CSR"),
                    ("foodservice_access", "Foodservice Access"),
                    ("beverage_access", "Beverage Access"),
                    ("container_access", "Container Access"),
                    ("carton_access", "Carton Access"),
                    ("graphic_specialist", "Graphic Specialist"),
                    ("pcss", "PCSS"),
                    ("shelbyville_platemaking", "Shelbyville Platemaking"),
                    ("kenton_platemaking", "Kenton Platemaking"),
                    ("shelbyville_art_approval", "Shelbyville Art Approval"),
                    ("kenton_art_approval", "Kenton Art Approval"),
                    ("visalia_art_approval", "Visalia Art Approval"),
                    ("pittston_art_approval", "Pittston Art Approval"),
                    ("clarksville_art_approval", "Clarksville Art Approval"),
                    ("clemson_employee", "Clemson Employee"),
                    ("demand_planning", "Demand Planning"),
                    ("is_fsb_csr", "Is FSB CSR"),
                    ("is_carton_csr", "Is Carton CSR"),
                    ("shelbyville_scheduling", "Shelbyville Scheduling"),
                    ("kenton_scheduling", "Kenton Scheduling"),
                    ("clemson_manager", "Clemson Manager"),
                    ("clemson_supervisor", "Clemson Supervisor"),
                    ("olmsted_falls_notification", "Olmsted Notification"),
                    ("foodservice_marketing", "Foodservice Marketing"),
                    ("accounting_access", "Accounting/Billing Access"),
                    ("job_entry", "Job Entry"),
                    ("job_general_edit", "Edit General Job Info"),
                    ("rename_item_folders", "Rename Item Folders"),
                ),
            },
        ),
    ]
