# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.CharField(blank=True, max_length=50)),
                ("last_page_request", models.DateTimeField(blank=True, null=True)),
                (
                    "total_vacation",
                    models.IntegerField(
                        default=0, editable=False, verbose_name=b"Total Vacation"
                    ),
                ),
                (
                    "growl_hear_approvals",
                    models.IntegerField(
                        choices=[
                            (0, b"Disabled"),
                            (1, b"Enabled"),
                            (2, b"Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name=b"Item Approvals",
                    ),
                ),
                (
                    "growl_hear_jdf_processes",
                    models.IntegerField(
                        choices=[
                            (0, b"Disabled"),
                            (1, b"Enabled"),
                            (2, b"Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name=b"JDF Events",
                    ),
                ),
                (
                    "growl_hear_new_beverage_jobs",
                    models.IntegerField(
                        choices=[
                            (0, b"Disabled"),
                            (1, b"Enabled"),
                            (2, b"Enabled - Sticky"),
                        ],
                        default=0,
                        verbose_name=b"New Beverage Jobs",
                    ),
                ),
                (
                    "growl_hear_new_foodservice_jobs",
                    models.IntegerField(
                        choices=[
                            (0, b"Disabled"),
                            (1, b"Enabled"),
                            (2, b"Enabled - Sticky"),
                        ],
                        default=0,
                        verbose_name=b"New Foodservice Jobs",
                    ),
                ),
                (
                    "growl_hear_9digit_entry",
                    models.IntegerField(
                        choices=[
                            (0, b"Disabled"),
                            (1, b"Enabled"),
                            (2, b"Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name=b"9-Digit Number Entries",
                    ),
                ),
                (
                    "growl_hear_whoops",
                    models.IntegerField(
                        choices=[
                            (0, b"Disabled"),
                            (1, b"Enabled"),
                            (2, b"Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name=b"Whoopsies!",
                    ),
                ),
                (
                    "growl_hear_revisions",
                    models.IntegerField(
                        choices=[
                            (0, b"Disabled"),
                            (1, b"Enabled"),
                            (2, b"Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name=b"New Revisions",
                    ),
                ),
                (
                    "growl_hear_plant_rejections",
                    models.IntegerField(
                        choices=[
                            (0, b"Disabled"),
                            (1, b"Enabled"),
                            (2, b"Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name=b"Plant Rejections",
                    ),
                ),
                (
                    "growl_hear_demand_planning_rejections",
                    models.IntegerField(
                        choices=[
                            (0, b"Disabled"),
                            (1, b"Enabled"),
                            (2, b"Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name=b"Demand Planning Rejections",
                    ),
                ),
                (
                    "growl_hear_job_db_uploads",
                    models.IntegerField(
                        choices=[
                            (0, b"Disabled"),
                            (1, b"Enabled"),
                            (2, b"Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name=b"Job Database Document Uploads",
                    ),
                ),
                (
                    "growl_hear_item_duplication",
                    models.IntegerField(
                        choices=[
                            (0, b"Disabled"),
                            (1, b"Enabled"),
                            (2, b"Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name=b"Item Duplications/Press Changes",
                    ),
                ),
                (
                    "growl_hear_gold_changes",
                    models.IntegerField(
                        choices=[
                            (0, b"Disabled"),
                            (1, b"Enabled"),
                            (2, b"Enabled - Sticky"),
                        ],
                        default=1,
                        verbose_name=b"GOLD Changes",
                    ),
                ),
                (
                    "growl_hear_todays_events",
                    models.IntegerField(
                        choices=[
                            (0, b"Disabled"),
                            (1, b"Enabled"),
                            (2, b"Enabled - Sticky"),
                        ],
                        default=2,
                        verbose_name=b"Today's Events",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("in_artist_pulldown", "In Artist Pulldown"),
                    ("salesperson", "Salesperson/Analyst/CSR"),
                    ("foodservice_access", "Foodservice Access"),
                    ("beverage_access", "Beverage Access"),
                    ("container_access", "Container Access"),
                    ("shelbyville_platemaking", "Shelbyville Platemaking"),
                    ("kenton_platemaking", "Kenton Platemaking"),
                    ("shelbyville_art_approval", "Shelbyville Art Approval"),
                    ("kenton_art_approval", "Kenton Art Approval"),
                    ("visalia_art_approval", "Visalia Art Approval"),
                    ("clemson_employee", "Clemson Employee"),
                    ("demand_planning", "Demand Planning"),
                    ("is_fsb_csr", "Is FSB CSR"),
                    ("shelbyville_scheduling", "Shelbyville Scheduling"),
                    ("kenton_scheduling", "Kenton Scheduling"),
                    ("clemson_manager", "Clemson Manager"),
                    ("olmsted_falls_notification", "Olmsted Notification"),
                    ("foodservice_marketing", "Foodservice Marketing"),
                    ("accounting_access", "Accounting/Billing Access"),
                    ("job_entry", "Job Entry"),
                    ("job_general_edit", "Edit General Job Info"),
                ),
            },
        ),
    ]
