# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="total_sick",
            field=models.IntegerField(
                default=5, editable=False, verbose_name=b"Total Sick"
            ),
        ),
    ]
