# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile_total_sick"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="machine_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
