# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_auto_20190118_1333"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "permissions": (
                    ("in_artist_pulldown", "In Artist Pulldown"),
                    ("salesperson", "Salesperson/Analyst/CSR"),
                    ("foodservice_access", "Foodservice Access"),
                    ("beverage_access", "Beverage Access"),
                    ("container_access", "Container Access"),
                    ("shelbyville_platemaking", "Shelbyville Platemaking"),
                    ("kenton_platemaking", "Kenton Platemaking"),
                    ("shelbyville_art_approval", "Shelbyville Art Approval"),
                    ("kenton_art_approval", "Kenton Art Approval"),
                    ("visalia_art_approval", "Visalia Art Approval"),
                    ("pittston_art_approval", "Pittston Art Approval"),
                    ("clarksville_art_approval", "Clarksville Art Approval"),
                    ("clemson_employee", "Clemson Employee"),
                    ("demand_planning", "Demand Planning"),
                    ("is_fsb_csr", "Is FSB CSR"),
                    ("shelbyville_scheduling", "Shelbyville Scheduling"),
                    ("kenton_scheduling", "Kenton Scheduling"),
                    ("clemson_manager", "Clemson Manager"),
                    ("olmsted_falls_notification", "Olmsted Notification"),
                    ("foodservice_marketing", "Foodservice Marketing"),
                    ("accounting_access", "Accounting/Billing Access"),
                    ("job_entry", "Job Entry"),
                    ("job_general_edit", "Edit General Job Info"),
                    ("rename_item_folders", "Rename Item Folders"),
                )
            },
        ),
    ]
