# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_auto_20190425_1344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="growl_hear_9digit_entry",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=2,
                verbose_name="9-Digit Number Entries",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="growl_hear_approvals",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=2,
                verbose_name="Item Approvals",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="growl_hear_demand_planning_rejections",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=2,
                verbose_name="Demand Planning Rejections",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="growl_hear_gold_changes",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=1,
                verbose_name="GOLD Changes",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="growl_hear_item_duplication",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=2,
                verbose_name="Item Duplications/Press Changes",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="growl_hear_jdf_processes",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=2,
                verbose_name="JDF Events",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="growl_hear_job_db_uploads",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=2,
                verbose_name="Job Database Document Uploads",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="growl_hear_new_beverage_jobs",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=0,
                verbose_name="New Beverage Jobs",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="growl_hear_new_foodservice_jobs",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=0,
                verbose_name="New Foodservice Jobs",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="growl_hear_plant_rejections",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=2,
                verbose_name="Plant Rejections",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="growl_hear_revisions",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=2,
                verbose_name="New Revisions",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="growl_hear_todays_events",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=2,
                verbose_name="Today's Events",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="growl_hear_whoops",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=2,
                verbose_name="Whoopsies!",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="total_sick",
            field=models.IntegerField(
                default=5, editable=False, verbose_name="Total Sick"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="total_vacation",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Total Vacation"
            ),
        ),
    ]
