# Generated by Django 2.2 on 2020-09-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_auto_20200217_1052"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="growl_hear_new_carton_jobs",
            field=models.IntegerField(
                choices=[(0, "Disabled"), (1, "Enabled"), (2, "Enabled - Sticky")],
                default=0,
                verbose_name="New Carton Jobs",
            ),
        ),
    ]
