# Generated by Django 5.2.5 on 2025-09-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='use_legacy_search',
            field=models.BooleanField(default=True, help_text='When enabled, job and item search will use the original GOLD interface', verbose_name='Use Legacy Search Interface'),
        ),
    ]
