# Generated by Django 5.2.5 on 2025-09-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_userprofile_use_legacy_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="item_search_brand",
            field=models.BooleanField(
                default=True,
                help_text="Include brand field in item searches",
                verbose_name="Search Brand Field",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="item_search_comments",
            field=models.BooleanField(
                default=True,
                help_text="Include comments field in item searches",
                verbose_name="Search Comments Field",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="item_search_customer",
            field=models.BooleanField(
                default=True,
                help_text="Include customer field in item searches",
                verbose_name="Search Customer Field",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="item_search_description",
            field=models.BooleanField(
                default=True,
                help_text="Include item description field in item searches",
                verbose_name="Search Item Description",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="item_search_specifications",
            field=models.BooleanField(
                default=True,
                help_text="Include specifications field in item searches",
                verbose_name="Search Specifications Field",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="item_search_upc",
            field=models.BooleanField(
                default=True,
                help_text="Include UPC field in item searches",
                verbose_name="Search UPC Field",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_search_artist",
            field=models.BooleanField(
                default=True,
                help_text="Include artist field in job searches",
                verbose_name="Search Artist Field",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_search_brand",
            field=models.BooleanField(
                default=True,
                help_text="Include brand field in job searches",
                verbose_name="Search Brand Field",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_search_comments",
            field=models.BooleanField(
                default=True,
                help_text="Include comments field in job searches",
                verbose_name="Search Comments Field",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_search_customer",
            field=models.BooleanField(
                default=True,
                help_text="Include customer field in job searches",
                verbose_name="Search Customer Field",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_search_instructions",
            field=models.BooleanField(
                default=True,
                help_text="Include instructions field in job searches",
                verbose_name="Search Instructions Field",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_search_po_number",
            field=models.BooleanField(
                default=True,
                help_text="Include PO number field in job searches",
                verbose_name="Search PO Number Field",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_search_salesperson",
            field=models.BooleanField(
                default=True,
                help_text="Include salesperson field in job searches",
                verbose_name="Search Salesperson Field",
            ),
        ),
    ]
