# Generated by Django 5.2.5 on 2025-09-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_userprofile_item_search_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Master switch to enable/disable all desktop notifications",
                verbose_name="Enable All Notifications",
            ),
        ),
    ]
