# Generated by Django 5.2.5 on 2025-09-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_add_notifications_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="custom_accent_color",
            field=models.CharField(
                blank=True,
                help_text="Custom hex color code for accent theme color (e.g., #28a745)",
                max_length=7,
                null=True,
                verbose_name="Custom Accent Color",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="custom_primary_color",
            field=models.CharField(
                blank=True,
                help_text="Custom hex color code for primary theme color (e.g., #007bff)",
                max_length=7,
                null=True,
                verbose_name="Custom Primary Color",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_animations",
            field=models.BooleanField(
                default=True,
                help_text="Enable smooth transitions and animations in the interface",
                verbose_name="Enable Animations",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_theme",
            field=models.CharField(
                choices=[
                    ("default", "Default Theme"),
                    ("dark", "Dark Theme"),
                    ("light", "Light Theme"),
                ],
                default="default",
                help_text="Choose your preferred color theme for the interface",
                max_length=20,
                verbose_name="Preferred Theme",
            ),
        ),
    ]
