# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KentonArchive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.CharField(max_length=255)),
                ("cd", models.CharField(blank=True, max_length=255)),
                ("art_reference", models.CharField(blank=True, max_length=255)),
                ("job_name", models.CharField(blank=True, max_length=30255)),
                (
                    "plates_ordered",
                    models.DateField(blank=True, null=True, verbose_name=b"Date Plates Ordered"),
                ),
                ("size", models.CharField(blank=True, max_length=255)),
                ("item_number", models.CharField(blank=True, max_length=255)),
                ("document_number", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RenMarkArchive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=255)),
                ("size", models.CharField(blank=True, max_length=255)),
                (
                    "folder_creation",
                    models.DateField(blank=True, null=True, verbose_name=b"Date Folder Created"),
                ),
                ("folder_items", models.TextField(blank=True)),
            ],
        ),
    ]
