# Generated by Django 2.2 on 2019-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kentonarchive",
            name="plates_ordered",
            field=models.DateField(blank=True, null=True, verbose_name="Date Plates Ordered"),
        ),
        migrations.AlterField(
            model_name="renmarkarchive",
            name="folder_creation",
            field=models.DateField(blank=True, null=True, verbose_name="Date Folder Created"),
        ),
    ]
