# Generated by Django 5.2.5 on 2025-08-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0002_auto_20190923_1111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kentonarchive",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="renmarkarchive",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
