name: CI

on:
  push:
    branches: [main, jb]
  pull_request:
    branches: [main, jb]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: gchub_test
          POSTGRES_USER: gchub
          POSTGRES_PASSWORD: gchub
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d gchub_test"
          --health-interval=5s --health-timeout=5s --health-retries=20
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev libxml2-dev libxslt-dev libffi-dev libssl-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f config/requirements-dev.txt ]; then pip install -r config/requirements-dev.txt; fi
          if [ -f config/requirements.txt ]; then pip install -r config/requirements.txt; fi
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1

      - name: Run ruff (selective)
        # In permissive dev mode we run ruff but don't fail the job on warnings;
        # this prevents style/docstring noise from blocking PRs while we
        # progressively clean the codebase. Critical failures (syntax/pyflakes)
        # should still be caught by the later test steps.
        run: |
          python -m ruff check . || true

      - name: Run security scan (bandit)
        run: |
          pip install bandit
          bandit -r . -f json -o bandit-report.json || true
          bandit -r . --exit-zero

      - name: Check for vulnerable dependencies (safety)
        run: |
          pip install safety
          safety check || true

      - name: Configure test Postgres env
        run: |
          echo "TEST_PG_NAME=gchub_test_${{ matrix.python-version }}" >> $GITHUB_ENV
          echo "TEST_PG_USER=gchub" >> $GITHUB_ENV
          echo "TEST_PG_PASSWORD=gchub" >> $GITHUB_ENV
          echo "TEST_PG_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "TEST_PG_PORT=5432" >> $GITHUB_ENV

      - name: Reset test database
        env:
          TEST_PG_NAME: ${{ env.TEST_PG_NAME }}
          TEST_PG_USER: ${{ env.TEST_PG_USER }}
          TEST_PG_PASSWORD: ${{ env.TEST_PG_PASSWORD }}
          TEST_PG_HOST: ${{ env.TEST_PG_HOST }}
          TEST_PG_PORT: ${{ env.TEST_PG_PORT }}
        run: |
          # Drop and recreate the test database to ensure clean state
          PGPASSWORD=${{ env.TEST_PG_PASSWORD }} psql -h ${{ env.TEST_PG_HOST }} -p ${{ env.TEST_PG_PORT }} -U ${{ env.TEST_PG_USER }} -d postgres -c "DROP DATABASE IF EXISTS ${{ env.TEST_PG_NAME }};"
          PGPASSWORD=${{ env.TEST_PG_PASSWORD }} psql -h ${{ env.TEST_PG_HOST }} -p ${{ env.TEST_PG_PORT }} -U ${{ env.TEST_PG_USER }} -d postgres -c "CREATE DATABASE ${{ env.TEST_PG_NAME }};"

      - name: Django makemigrations check
        env:
          DJANGO_SETTINGS_MODULE: gchub_db.test_settings
          TEST_PG_NAME: ${{ env.TEST_PG_NAME }}
          TEST_PG_USER: ${{ env.TEST_PG_USER }}
          TEST_PG_PASSWORD: ${{ env.TEST_PG_PASSWORD }}
          TEST_PG_HOST: ${{ env.TEST_PG_HOST }}
          TEST_PG_PORT: ${{ env.TEST_PG_PORT }}
        run: |
          # wait for Postgres
          for i in {1..30}; do pg_isready -h 127.0.0.1 -p 5432 -U postgres && exit 0 || sleep 2; done
          python manage.py makemigrations --check --settings=gchub_db.test_settings

      - name: Apply migrations
        env:
          DJANGO_SETTINGS_MODULE: gchub_db.test_settings
          TEST_PG_NAME: ${{ env.TEST_PG_NAME }}
          TEST_PG_USER: ${{ env.TEST_PG_USER }}
          TEST_PG_PASSWORD: ${{ env.TEST_PG_PASSWORD }}
          TEST_PG_HOST: ${{ env.TEST_PG_HOST }}
          TEST_PG_PORT: ${{ env.TEST_PG_PORT }}
        run: |
          python manage.py migrate --settings=gchub_db.test_settings --noinput

      - name: Run tests (pytest)
        env:
          DJANGO_SETTINGS_MODULE: gchub_db.test_settings
          TEST_PG_NAME: ${{ env.TEST_PG_NAME }}
          TEST_PG_USER: ${{ env.TEST_PG_USER }}
          TEST_PG_PASSWORD: ${{ env.TEST_PG_PASSWORD }}
          TEST_PG_HOST: ${{ env.TEST_PG_HOST }}
          TEST_PG_PORT: ${{ env.TEST_PG_PORT }}
        run: |
          pytest --cov=. --cov-report=html --cov-report=term-missing --cov-report=xml

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
